### ISSUE TITLE
Problem: no "non-zero fee integration test"

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1002]
currently, there is no integration test for "non-zero fee"
add "non-zero fee" integration test.
if possible, perform both types of test for 4 txs
1) deposit
2) unbond
3) withdrawal
4) transfer between utxo

**Comment by yihuang** [comment]
Aren't there withfee typescript integration-tests? Maybe the test cases are not enough?

**Comment by tomtau** [comment]
@leejw51crypto -- AFAIK there are two configurations for integration tests, one with zero fee, one with non-zero fee:
https://github.com/crypto-com/chain/blob/master/integration-tests/with_fee_cluster.json
https://github.com/crypto-com/chain/blob/master/integration-tests/zero_fee_cluster.json

**Comment by tomtau** [comment]
and they seem to execute for most tx types: https://github.com/crypto-com/chain/blob/master/integration-tests/client-rpc/test/wallet-transaction.test.ts
`unbondAndWithdrawStake`
then `wallet_sendToAddress` does transfer.

maybe `deposit` is missing, @calvinaco  ?

**Comment by leejw51crypto** [comment]
non-zero fee test is already included
