### ISSUE TITLE
Problem: no packaging for cro

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1003]
provide compiled binary for running these sub-processes
receive APP_HASH, SPID, IAS_API_KEY as environment variables from end user.
consider compiled go-lang supervisord or writing launcher with RUST using ipc if necessary
provide zipped file to end-user
1) tx-query
2) tx-validation-app
3) chain-abci
4) tendermint
5) client-rpc

**Comment by tomtau** [comment]
binary tarballs are here: https://github.com/crypto-com/chain/releases

For launching https://github.com/crypto-com/chain/blob/master/Makefile#L306 does this

if there's something else missing, feel free to comment
