### ISSUE TITLE
Problem: client doesn't validate transactions it generates

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1004]
add some context specific information in the error message
for example)
if incoins < total_outsum.unwrap() {
        let gap= total_outsum - incoins;
        let info=format!("more {} coin is necessary for fee in check_input_output_sums ", gap);
        return Err(Error::InputOutputDoNotMatch, gap);
}

**Comment by tomtau** [comment]
@leejw51crypto I changed the title -- with errors from tx-validation, it needs to be more careful, so that it doesn't leak information.
It'd be better if client tried to validate transactions it generated rather than broadcasting "whatever" wrong transactions
