### ISSUE TITLE
Problem: no separation of wallet and sync storage

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1021]
if we store only wallet information as separate folder, backup will be easier
.wallet-storage <- only for wallet
.sync-storage <- only for sync
.cro-storage <- chain core

**Comment by yihuang** [comment]
Kind of duplicate of #827? As long as we can backup wallet, no need to separate storage?

**Comment by tomtau** [comment]
yeah, looks like a duplicate
