### ISSUE TITLE
Problem: complex fee policy

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1025]
compute fee based upon raw byte size before encryption.
in encrypted data, add original raw byte size for verification

by this algorithm, fee computing is deterministic only to raw byte size.
no need to emulate tx-query-app.
just need to know linear fee algorithm parameters

**Comment by tomtau** [comment]
@leejw51crypto 

1. why is looping a problem?
2. what looping?
There's only looping for UTXO selection AFAIK (see strategies https://iohk.io/en/blog/posts/2018/07/03/self-organisation-in-coin-selection/ ) -- not sure how it can be done without it? The only way may if every transaction includes all UTXOs (known to the wallet) as transaction inputs regardless of the value, but that potentially increases the fee + forces wallet transactions to be linear (so not possible to submit several transactions in parallel from one wallet).

One could add a "loop-less" UTXO selection strategy, but not sure if it's worth it?

**Comment by leejw51crypto** [comment]
yes, selecting specific utxo is not part of consensus.
it's OK.
how about computing fee with raw size before encryption?

it will make fee computing logic very simple.
base + coeff * raw_tx_serialized_length == computed fee
because currently, there're "different input/output pins error" take place sometimes.

encrypted tx, can carry original raw byte size, so it will be ok in verification.

**Comment by linfeng-crypto** [comment]
the difference of fee comes from the difference number of utxo, the fee is same if the number of utxo is same, so we can find a function like `f(x) = a*x + b`, where x is the number of utxo. If the result can be same with the one calcuated by current algo's,  we can use `f(x)`. We can even make some modify on `f(x)` such as give some limit like `fee_max` or `fee_min`, then we don't need the `dummy signer`

**Comment by tomtau** [comment]
As per discussion on Slack, the fee policy itself is ok (it doesn't really matter on whether one takes bytes, number of items, and whether it's post- or pre-obfuscation in certain tx types).
There are some bugs in fee estimation, e.g. https://github.com/crypto-com/chain/issues/1001
but they should be resolved.
If there are other concerns, feel free to discuss on Slack
