### ISSUE TITLE
Problem: entering wallet name, enckey continuously in client-cli

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1026]
in client-cli, cache "wallet name", "enckey" to memory.
so don't need to type again.
also for other information, store latest value except for coin value.
currently, user need to copy and paste many times

**Comment by yihuang** [comment]
Good to define several environment variables, when it's set in environment variables, client-cli doesn't need to ask again.
- `WALLET_NAME`
- `PASSPHRASE`
- `AUTH_TOKEN`

**Comment by tomtau** [comment]
As this is nearly a duplicate issue to https://github.com/crypto-com/chain/issues/960 , I'll close this re-open that one
