### ISSUE TITLE
Problem: node with a jailed staked state remains/returns as an active validator

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1034]
Observed on 0.2.1 testnet:

* eastus2 node validator was restarted at about 1.30 AM on 2020-02-08 and due to a missing /dev/sgx, it failed to start up (tx-validation-app didn't start up -> chain-abci didn't start up -> tendermint didn't start up) ... between blocks 71904 and 71905
* (some time later, the associated staked state was jailed -- not sure exactly when @lezzokafka )
* around 10 AM on 2020-02-08, I fixed the node (reinstalled SGX driver) -- all running and syncing ... at that time, the node didn't appear to be in the validator set (e.g. not in `/validators` or with 0 in `abci_query` of `council-nodes`)
* now, the node is a part of the validator set (address `AECD188A8F9372847665D655F15D2BBDAE1494D0` / pub key: `nUNb5erLD6n61TQ7g6ZlRk067kwzs2tuH8bSro07JlI=`), yet its associated stake state (address: `0x6dbd5b8fe0dad494465aa7574defba711c184102`) is jailed

**Comment by lezzokafka** [comment]
<img width="453" alt="Screen Shot 2020-02-10 at 11 12 48 am" src="https://user-images.githubusercontent.com/51898510/74119331-ecccb500-4bf9-11ea-8fa3-1a5a9ba0e281.png">

@tomtau 
` | Jailed Until    | 2020-02-09 02:56:39 +08:00 |` gave us some insights: 

As the `jail_duration` is set to be `86400` (1 Day) in the current config, we know that it was jailed 
_2020-02-08 02:56:39 +08:00_

**Comment by yihuang** [comment]
- No join-node tx sent?
- tendermint version?

**Comment by tomtau** [comment]
@yihuang I didn't. not sure if @devashishdxt or @lezzokafka sent node join tx
tendermint version 0.32.8

**Comment by devashishdxt** [comment]
Neither did I.

**Comment by tomtau** [comment]
yeah, so probably no node join tx

**Comment by lezzokafka** [comment]
@yihuang nope

**Comment by tomtau** [comment]
note that this may be due to / disappear with https://github.com/crypto-com/chain/issues/930 but it'll be good to try to reproduce it

**Comment by tomtau** [comment]
(i.e. the root cause of data not being cleaned up)

**Comment by tomtau** [comment]
Some extra info discovered by @lezzokafka -- validator re-joined the validator set after reward distribution.
This is likely due to: https://github.com/crypto-com/chain/blob/release/v0.2/chain-abci/src/app/rewards.rs#L104

**Comment by yihuang** [comment]
> Some extra info discovered by @lezzokafka -- validator re-joined the validator set after reward distribution.
> This is likely due to: https://github.com/crypto-com/chain/blob/release/v0.2/chain-abci/src/app/rewards.rs#L104

Yeah, it looks like it, if settings the `power_changed_in_blocks` will cause it to become a validator again.
I'm quite confused with current state interactions.

**Comment by tomtau** [comment]
In the current validator state interactions, `power_changed_in_blocks` / most direct updates were hidden... punishments are updated with https://github.com/crypto-com/chain/blob/master/chain-abci/src/app/app_init/validator_state.rs#L595 
and punished nodes are removed from validator statistics: https://github.com/crypto-com/chain/blob/master/chain-abci/src/app/app_init/validator_state.rs#L263

so this may have been fixed, but it should be verified whether this cannot happen in other edge cases. and perhaps reward distribution should have extra checks to exclude jailed accounts
