### ISSUE TITLE
Problem: no total supply sanity checks

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1038]
Currently coins can reside in several places:
1. staked states (bonded or unbonded)
2. rewards pool (not-yet-minted coins or bonus from fees and punishments)
3. transfer transaction outputs

different state updates then move these around.
It'll be good to have some high-level statistics tracking on these 3 areas, which will be updated on each change + an invariant that sum(1.'s amount + 2.'s amount + 3.'s amount) == maximum supply.
there could be fuzzing tests that would try to break this invariant

**Comment by yihuang** [comment]
Current checkpoints:
- In genesis:
  ```
  monetary_expansion_cap + distribution = maximum supply
  ```

- In reward distribution, the total minted coins are recorded and checked to not exceed `monetary_expansion_cap`.

**Comment by tomtau** [comment]
For UTXO "sum", it'll just be recording "withdraw"

**Comment by yihuang** [comment]
- record total utxo amount
- total utxo amount + expansion_cap + total staking amount + reward pool = max supply
- in mock mode, check total utxo amount against the utxo set
- do the check at the end of each deliver_tx, and end_block in debug mode.
