### ISSUE TITLE
Problem: no client-cli to utxo directly

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1049]
add utxo command to client-cli
as follows
display utxo which belongs to specified wallet
./client-cli utxo list --name a
print-outs for each utxo
address, coin, timelock  

this is current utxo, if it's consumed, it's removed

**Comment by yihuang** [comment]
Currently, my workflow is more like start a full node, use `chainrpc.py` to interact with `client-rpc`, barely needs `client-cli`.

**Comment by tomtau** [comment]
@leejw51crypto there's this issue: https://github.com/crypto-com/chain/issues/968 @devashishdxt is working on ... it won't display all utxos, but it'll give you details about a transaction, so you can see which outputs are spent or not

**Comment by leejw51crypto** [comment]
ok

**Comment by leejw51crypto** [comment]
it's resolved by another issue.
