### ISSUE TITLE
Problem: No integration-tests CI running in the cloud automatically

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1050]
Since the scripts for building and running mock version of integration-tests are in place, it's now trivial to setup a mock version of drone config(`.drone.mock.yml`) which can runs on [drone cloud](https://cloud.drone.io/) automatically.

**Comment by tomtau** [comment]
@yihuang https://cloud.drone.io/crypto-com/chain/settings
added the config -- since the mock doesn't need trusted execution, I guess this could execute against anything

**Comment by tomtau** [comment]
Drone Cloud may have a bit faster execution, so we may consider executing "cargo kcov" there
