### ISSUE TITLE
Problem: no integration test for proportional slashing

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1061]
currently, there are only a few isolated unit tests

**Comment by yihuang** [comment]
Seems the simplest solution is like this:
- Prepare 5 nodes
- node0 has more than 2/3 powers, to keep running after all other jailed.
- node1 and node2 have the same validator pubkey.
- node3 and node4 have the same validator pubkey.
- node2 and node4 has zero bonded coin to keep the genesis distribution valid.
- set `create_empty_blocks_interval` to `10s` for better stability.
- Start the whole thing, wait for the first block to popup, node1-4 will be jailed at the same time, after slash wait period, verify the slashed amount.

**Comment by yihuang** [comment]
Oh, no, even with this setup, the byzantine faults are not detected in the same block.

**Comment by tomtau** [comment]
what about liveness faults? shutdown several nodes at the same time?

**Comment by yihuang** [comment]
> what about liveness faults? shutdown several nodes at the same time?

Sounds better, we can init with three validators in the genesis, but only start one, should produce non-live faults at the same time stablely.

**Comment by devashishdxt** [comment]
On a side node: Current implementation of proportional slashing works a bit differently than intended. The proportionality is based on the number of faults detected in a block whereas it should be based on the number of faults committed in a block. It'll get fixed once crypto-com/chain-docs#89 is implemented.

**Comment by yihuang** [comment]
- If we only start node0 without starting other nodes, even if node0 has more than 2/3 voting powers, it won't start generating blocks.
- If we start three nodes first, then stop node1/node2 immediately, we still have stability issue, we can't be sure they are stopped at the same block.
