### ISSUE TITLE
Problem: No command to recover the authentication token in client-cli

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#1070]
Currently there is no command in client-cli for recovering the authentication token.

What to expect: 
- Commands like `./client-cli token --name <wallet_name>` for recovering the token.

**Comment by tomtau** [comment]
@lezzokafka I think there is, it's called "wallet auth-token".
Anyway, in general inputting auth token isn't a good CLI UX -- there's an issue for this: https://github.com/crypto-com/chain/issues/960
