### ISSUE TITLE
Problem: staked state slashed, but not jailed

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1079]
v0.2.1 chain-abci fails with:
> abci[1416]: thread 'tokio-runtime-worker-0' panicked at 'Account scheduled for slashing should already be jailed', chain-abci/src/app/slash_accounts.rs:57:17

The affected address seems to be 0x4ae85b35597fcb61c6c47b1fe0bdd7eed8421cdd.

@calvinaco backed up all node data.
It'll be worth digging out whether this was fixed or it is a new bug, like https://github.com/crypto-com/chain/issues/1045

**Comment by yihuang** [comment]
Is the constraint `jail_duration > slash_wait_period` satisfied in configuration?

**Comment by devashishdxt** [comment]
> Is the constraint `jail_duration > slash_wait_period` satisfied in configuration?

Yes. This was the configuration for testnet v0.2.1:
```
"network_params": {
    "jailing_config": {
        "block_signing_window": 360,
        "jail_duration": 86400,
        "missed_block_threshold": 180
    },
    "slashing_config": {
        "byzantine_slash_percent": "0.200",
        "liveness_slash_percent": "0.100",
        "slash_wait_period": 10800
    },
    "unbonding_period": 3600
}
```

**Comment by tomtau** [comment]
not relevant after https://github.com/crypto-com/chain/pull/1292
