### ISSUE TITLE
Problem: `slash_proportion` calculation is problematic.

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1096]
Seperated from #1045 .

Current slash_proportion is calculated like this:
```
total_voting_power = sum(voting power of active validators)
sum(sqrt(voting_power / total_voting_power foreach faulting validators)) ^ 2
```
- The calculation is done with `Millis`, so if faulting_voting_power is relatively small, the result is zero.
- The calculation is based on voting power which reflects bonded coins, if when the fault is detected, validator already unbonded the coins, he will get a very small(even zero) `slash_ratio`.

**Comment by tomtau** [comment]
* calculation with milli -- https://github.com/crypto-com/chain/issues/805 -- we can switch to "fixed", but before that, it'll be good to review and vendor in its relevant / used parts of code, so that we have some understanding what's happening (and it can specified precisely) rather than it being done blackbox in an external library

* The calculation is based on voting power which reflects bonded coins: the good starting point are the revised docs https://github.com/crypto-com/chain-docs/issues/84 https://github.com/crypto-com/chain-docs/issues/79

**Comment by devashishdxt** [comment]
>     * The calculation is based on voting power which reflects bonded coins: the good starting point are the revised docs [crypto-com/chain-docs#84](https://github.com/crypto-com/chain-docs/issues/84) [crypto-com/chain-docs#79](https://github.com/crypto-com/chain-docs/issues/79)

I'm on it!

**Comment by yihuang** [comment]
> > ```
> > * The calculation is based on voting power which reflects bonded coins: the good starting point are the revised docs [crypto-com/chain-docs#84](https://github.com/crypto-com/chain-docs/issues/84) [crypto-com/chain-docs#79](https://github.com/crypto-com/chain-docs/issues/79)
> > ```
> 
> I'm on it!

So we talk about this issue after the docs polishment? I'm not sure this is inherent in the original spec, or it's an implementation issue.

**Comment by devashishdxt** [comment]
> > > ```
> > > * The calculation is based on voting power which reflects bonded coins: the good starting point are the revised docs [crypto-com/chain-docs#84](https://github.com/crypto-com/chain-docs/issues/84) [crypto-com/chain-docs#79](https://github.com/crypto-com/chain-docs/issues/79)
> > > ```
> > 
> > 
> > I'm on it!
> 
> So we talk about this issue after the docs polishment? I'm not sure this is inherent in the original spec, or it's an implementation issue.

You can post your comments here: https://github.com/crypto-com/chain-docs/pull/89

**Comment by tomtau** [comment]
not relevant after https://github.com/crypto-com/chain/pull/1292 as calculation was simplified not to have proportions
