### ISSUE TITLE
Problem: repeated db open/close and thread spawning `jsonrpc_call` C binding

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1132]
as mentioned by @yihuang https://github.com/crypto-com/chain/pull/1122#issuecomment-590144475
this could be optimised

**Comment by leejw51crypto** [comment]
i'm thinking this flow

db=cro_db_open()
json_call(......, db) 
cro_db_close(db)

**Comment by yihuang** [comment]
> i'm thinking this flow
> 
> db=cro_db_open()
> cro_json_call(......, db)
> cro_db_close(db)

It's not only about DB, but there are also other resources, I suggest:
```
cro_json_open()  // return the pointer to Box<IoHandler>
cro_json_call()
cro_json_close()

cro_json_execute()  // automatically open/close
```

**Comment by leejw51crypto** [comment]
got it,
started

**Comment by leejw51crypto** [comment]
done.
in code-review
