### ISSUE TITLE
Problem: no way to get progress from sync in `jsonrpc_call` C API

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1133]
could be some stream watch function? @yihuang https://github.com/crypto-com/chain/pull/1122#issuecomment-590678357

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done,
now writing testing code

**Comment by leejw51crypto** [comment]
pr submitted

**Comment by leejw51crypto** [comment]
in code-review
