### ISSUE TITLE
Problem: no direct compilation in Makefile on linux

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1161]
currently, cargo build only compiles rust files not including enclave files.
add direct compile into Makefile.
also if intel sgx is already installed, not use docker in compiling

by docker compiling, some root owned files are generated inside
'target/debug/incremental',
if we support direct compiling, those artifacts can be removed

also fast compiling as well

for example)
so user just run
"make" in linux,
it builds all automatically including enclave so files.

**Comment by yihuang** [comment]
`./docker/build.sh`
