### ISSUE TITLE
Problem:sgx driver not active after os upgrade

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1164]
when apt upgrade,
sgx driver is sometimes not detectable, so tx-query-app cannot run

when sgx driver is not detected, display some guide how to fix it.
and also add some comments to the document
1. sgx driver location to download or compile , especially mention about ASUS mainboard.
2. method to check sgx availiability
3. display some message "do not upgrade os withtout checking sgx driver working valid"

**Comment by tomtau** [comment]
Isn't this more for Intel repo, not us?
