### ISSUE TITLE
Problem: TxoIndex is misused to refer to output size 

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1223]
it'll be good to have an explicit name for it -- e.g. TxoSize

**Comment by yihuang** [comment]
We want to have `TxoSize` used both for size and index right, just like `usize`?

**Comment by tomtau** [comment]
yeah, maybe that's fine and still meaningful, as with `usize`

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
i'll change
TxoIndex -> TxoSize

like usize,
just TxoSize seems OK

**Comment by leejw51crypto** [comment]
in code-review
