### ISSUE TITLE
Problem: no ABCI app versioning

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1232]
https://tendermint.com/docs/spec/abci/abci.html#info AppVersion is u64 and is included in every BlockHeader… 

+ checking including it in TX binary format, so validation will check that the received transaction's version <= current version

**Comment by calvinaco** [comment]
@tomtau It suddenly comes into my mind. I am wondering do we have API/abci_query to get the app version?

**Comment by tomtau** [comment]
@calvinaco yes, after this PR: https://github.com/crypto-com/chain/pull/1239 version should be returned in "Info" response (it also returns the tendermint versioning info)
