### ISSUE TITLE
Problem: infeasible to create a large chunk of transfer addresses in HD wallet in client-*

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1233]
this blocks @calvinaco experiments, it takes about 15 minutes to generate about 2000 addresses with client-rpc -- it becomes infeasible to generate 100,000s of addresses.
potential root causes: cryptographic generation, file system (sled) writing, ...
1. profile code first to see what takes most time
2. fix that

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
create transfer address time 623.216µs
create transfer address time 883.874µs
create transfer address time 677.78µs
create transfer address time 1.1154ms
create transfer address time 671.108µs
client-rpc creation time per 1 tx-address

start writing batch

**Comment by leejw51crypto** [comment]
in code-review
