### ISSUE TITLE
Problem: no Java example for C bindings

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1236]
Before there's a "Java SDK", it'll be good to have at least a small example with Java Native Interface and C bindings. Maybe just a simple example that takes Java Strings (or byte arrays/buffers?) -- https://docs.rs/jni/0.15.0/jni/ and calls the RPC method ?

**Comment by leejw51crypto** [comment]
ok

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done
sumitted pr
