### ISSUE TITLE
Problem: client-rpc may include duplicate view keys

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1242]
1. unbond
2. withdraw
inside WithdrawUnbondedStakeTransaction,
TxAttributes-> allowed_view->TxAccessPolicy
two same policies, modify with just one

**Comment by tomtau** [comment]
? it's per transaction

**Comment by leejw51crypto** [comment]
yes , per txs,
it's redundant,
maybe we can add in verification.

**Comment by tomtau** [comment]
ref: https://github.com/crypto-com/chain/blob/master/client-rpc/src/rpc/staking_rpc.rs#L322

**Comment by tomtau** [comment]
Similar problem was fixed before in client-cli: https://github.com/crypto-com/chain/pull/841

**Comment by tomtau** [comment]
maybe abstract out these similar TX-construction parts into client-core to be shared between client-rpc and client-cli
