### ISSUE TITLE
Problem: sgx-cargo-1804-hw1 is not easy to run locally

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1296]
Maybe move it into default pipeline, or change pipeline type to default.
Easier to test locally with drone-cli.

**Comment by tomtau** [comment]
It'll make sense to put it in the default pipeline, as it's all in Docker anyway now.
Local execution is easy though -- just run the same command?
```
docker run --name <SOME_NAME> --rm -v <PATH_TO_CHAIN_REPO>:/chain --device /dev/sgx cryptocom/chain:latest /bin/bash /chain/ci-scripts/tx-validation-hw-test.sh
```

It's expected to run in HW mode... for quick ad-hoc testing in SW mode, it's just steps from tx-validation-hw-test.sh without AESM+device testing + `export SGX_MODE=SW`

**Comment by yihuang** [comment]
It seems quite easy to run in the default pipeline, so I just did it.

```
drone exec --trusted --include sgx-test
```
