### ISSUE TITLE
Problem: Not able to do sanity check on max coin supply in chain-abci

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1327]
Because the content of UTxO is obfuscated.
Potential solutions:
- Tracking the total amount of UTxO set, because UTxO operations are relatively simpler, we can trust the UTxO tracking won't go wrong.
- Not obfuscate amount field in UTxO.

**Comment by tomtau** [comment]
duplicate of https://github.com/crypto-com/chain/issues/1038

"Tracking the total amount of UTxO set" is the only option, as the latter solution defeats the purpose of obfuscation
