### ISSUE TITLE
Problem: MerkleTree uses H256 instead of blake3::Hash

### ISSUE THREAD

**Issue by devashishdxt** [crypto-com/chain#1332]
`MerkeTree` implementation should ideally use `blake3::Hash` instead of `[u8; 32]` which provides constant-time equality checking.

**Comment by tomtau** [comment]
replaced in https://github.com/crypto-com/chain/commit/eb1d854c7439ad94a43d1f474b695cc99c7395ee#diff-47d71db49eaf5cc8e7785404daf784d2R181 in proof checking
