### ISSUE TITLE
Problem: outdated sample-chain-wallet 

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1341]
Solution: update with the latest master

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done

**Comment by leejw51crypto** [comment]
submitted pr
now follow up pr

**Comment by tomtau** [comment]
should work now with the latest master, even though the functionality is missing https://github.com/crypto-com/chain/issues/1416
