### ISSUE TITLE
Problem: Tendermint websocket client does not support connecting over TLS

### ISSUE THREAD

**Issue by devashishdxt** [crypto-com/chain#1346]

**Comment by devashishdxt** [comment]
I tried the most straight forward approach but quickly hit a few roadblocks. Current design of `WebsocketRpcClient` reads all the incoming messages over TCP from one thread, writes to the stream from a different thread (to support multiple requests and responses) and maps request and responses with their `id`s. `websocket` crate had a `.split()` function to split the websocket stream into two parts (`Reader` and `Writer`) and `tungstenite` doesn't have such method. Current solution is cloning the underlying `TcpStream` using `TcpStream::try_clone` to get two handles and use one for reading and other for writing. But, when we use TLS, we cannot clone the stream which makes it impossible to support multiple requests/responses from client.

Solution for this is to move to `tokio-tungstenite` (which'll bring a lot of `tokio` related dependencies and also we need to figure out a way to plug `async` code into `sync` code).

Any comments/suggestions @yihuang @tomtau @leejw51crypto @linfeng-crypto?

**Comment by yihuang** [comment]
There are `socket.write_message` and `socket.read_message`, both can be called from multiple threads, right?

**Comment by devashishdxt** [comment]
> There are `socket.write_message` and `socket.read_message`, both can be called from multiple threads, right?

Both need mutable access. So I tried wrapping `WebSocket` in `Arc<Mutex<..>>` and pass it to different threads. But when we lock the mutex and call `socket.read_message` (which blocks until there is a new message of stream), we cannot write anything to websocket from other thread (because the `Mutex` is locked).

**Comment by yihuang** [comment]
https://github.com/snapview/tungstenite-rs/issues/11#issuecomment-293187432

> If the underlying stream is non-blocking, tungstenite-rs will work in a non-blocking mode. In other words, it solely depends on the stream you pass to the function. You can pass a TcpStream object from mio and then you can use it in a non-blocking manner.

**Comment by devashishdxt** [comment]
> [snapview/tungstenite-rs#11 (comment)](https://github.com/snapview/tungstenite-rs/issues/11#issuecomment-293187432)
> 
> > If the underlying stream is non-blocking, tungstenite-rs will work in a non-blocking mode. In other words, it solely depends on the stream you pass to the function. You can pass a TcpStream object from mio and then you can use it in a non-blocking manner.
> 
> With non-blocking mode, maybe you can do something like:
> 
> ```
> loop {
>    let ws = mutex.lock();
>    while let Some(msg) = ws.read_message() {
>         process
>    }
> }
> ```

Yes. But instead of manually doing all the `mio` stream juggling, we can use `tokio-tungstenite` (which internally does the same thing and also supports TLS). Or do you suggest that we should directly use `mio`?

**Comment by yihuang** [comment]
> > [snapview/tungstenite-rs#11 (comment)](https://github.com/snapview/tungstenite-rs/issues/11#issuecomment-293187432)
> > > If the underlying stream is non-blocking, tungstenite-rs will work in a non-blocking mode. In other words, it solely depends on the stream you pass to the function. You can pass a TcpStream object from mio and then you can use it in a non-blocking manner.
> > 
> > 
> > With non-blocking mode, maybe you can do something like:
> > ```
> > loop {
> >    let ws = mutex.lock();
> >    while let Some(msg) = ws.read_message() {
> >         process
> >    }
> > }
> > ```
> 
> Yes. But instead of manually doing all the `mio` stream juggling, we can use `tokio-tungstenite` (which internally does the same thing and also supports TLS). Or do you suggest that we should directly use `mio`?

Yeah, maybe we should just use tokio.

**Comment by tomtau** [comment]
tokio dependencies are already in Cargo.lock -- what additional things will it bring?

**Comment by devashishdxt** [comment]
> tokio dependencies are already in Cargo.lock -- what additional things will it bring?

I don't think it'll bring a lot of new tokio related functionalities (as they're already in `Cargo.lock`). It'll only bring `native-tls` and its dependencies.

**Comment by tomtau** [comment]
most of transitive dependencies of native-tls should be there -- e.g.: `security-framework` and `schannel` come from `rustls-native-certs` (... from `reqwest` in `ra-sp-server`)
