### ISSUE TITLE
Problem: no address discovery after wallet recovery

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1396]
in hdwallet, after wallet recovery,
balance is incorrect, because transfer addresses are not made yet
possible solution would be,
i suggest
1. in recovery wallet , also receive address generation count both for staking, transfer
2. recover wallet, and also generate addresses
3. so in sync, user can get latest balance

**Comment by tomtau** [comment]
@leejw51crypto I guess one other way is to generate new addresses in sync -- for HW wallets, it can keep XPub: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#public-parent-key--public-child-key
The sync logic will assume that addresses are generated:
- start with Addr_i (i = 0 or whatever was the latest)
- if you detect a deposit on Addr_i, derive Addr_(i+1) (set i = i + 1)

that way, the addresses are deterministically generated "one ahead" for the next payment

**Comment by yihuang** [comment]
> @leejw51crypto I guess one other way is to generate new addresses in sync -- for HW wallets, it can keep XPub: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#public-parent-key--public-child-key
> The sync logic will assume that addresses are generated:
> 
> * start with Addr_i (i = 0 or whatever was the latest)
> * if you detect a deposit on Addr_i, derive Addr_(i+1) (set i = i + 1)
> 
> that way, the addresses are deterministically generated "one ahead" for the next payment

This assumes every transfer address is used on chain in correct order, but that might not the case.

**Comment by yihuang** [comment]
We can keep a window of unused addresses, and with the help of the client logic to enforce that.
So we can change the logic to:
- if you detect a deposit on Addr_i, derive Addr_(i+1 .. i+W)

**Comment by leejw51crypto** [comment]
um, make sense

**Comment by tomtau** [comment]
following BIP44 is the most sensible, as it'll make the behaviour consistent across different wallet software

**Comment by tomtau** [comment]
recovery can have option to run sync which will follow the BIP44 account discovery procedure

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done.
now tidy up
