### ISSUE TITLE
Problem: Wallet sync is not working when fast forward is enabled

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain#1398]
### Brief description of the problem:
- When trying to `wallet_sendToAddress` from the same wallet twice, second transactions is not synced

### How to reproduce:
- Call `wallet_sendToAddress` to transfer from account A to any address
- Sync wallet
- Call `wallet_sendToAddress` to transfer from the same account A to any address
- Sync wallet using `sync` or `sync_all`
- Call `wallet_transactions`, `wallet_listUTxO` could not find the transactions and UTXOs
- Call `wallet_sendToAddress` would result in `Transaction already spent` error

### Possible related issues

https://github.com/crypto-com/chain/commit/5f2192eb3773afbe1639122b55a6fe2cf50e16b2

**Comment by yihuang** [comment]
Yes, this happens in zero-fee env, so the parameter `--disable-fast-forward` is added in integration tests environment.

**Comment by lezzokafka** [comment]
@yihuang, Yes, example on client-cli:
- Normal force sync
![Screen Shot 2020-04-07 at 6 06 14 pm](https://user-images.githubusercontent.com/51898510/78656999-ba3df080-78fa-11ea-8527-bc8fcb29875a.png)
- With  `--disable-fast-forward`
![Screen Shot 2020-04-07 at 6 07 21 pm](https://user-images.githubusercontent.com/51898510/78657015-c0cc6800-78fa-11ea-907f-6e2ea3d46c24.png)

**Comment by calvinaco** [comment]
Looping @allthatjazzleo

**Comment by calvinaco** [comment]
I am closing this because it is an known issue.

**Comment by yihuang** [comment]
This is a legitimate issue though, ultimately it will be solved by #794.
