### ISSUE TITLE
Problem: no address generation, unbond, withdraw, deposit in sample wallet

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1416]
add these feature
1. address generation: staking, transfer
2. unbond
3. withdraw
4. deposit
use current angular code-base

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
working on sync progress

**Comment by leejw51crypto** [comment]
progress report done

**Comment by leejw51crypto** [comment]
fixed update glitch
tidying up

**Comment by leejw51crypto** [comment]
withdraw, deposit, unbond
address generation done

in code-review

**Comment by tomtau** [comment]
resolved by https://github.com/crypto-com/sample-chain-wallet/pull/59
