### ISSUE TITLE
Problem:outdated dev-utils example

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1434]
in dev-utils, 
example-dev-conf.json is outdated.

add "cert" in council node
```
./dev-utils genesis generate --genesis_dev_config_path  ./dev.json
```
make sure that above command works fine

**Comment by yihuang** [comment]
Also, better to make it print more detailed error message, currently it only says:
```
$ ./target/debug/dev-utils genesis generate --genesis_dev_config_path dev-utils/example-dev-conf.json
Error: Deserialization error: failed to parse genesis dev config
```

**Comment by tomtau** [comment]
would be good to check it in Travis CI
