### ISSUE TITLE
Problem: Missing amount data around staking account transactions

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain#1435]
## Background
The bonded, unbonded amount can be query in `staking_state` API. However, if you are parsing the blocks transaction data and events, some of the amount data is missing and you cannot reproduce the exact same state.

#### Deposit Tx
- Deposit amount

#### Withdraw Tx
- Withdraw amount

**Comment by yihuang** [comment]
- Deposit amount is `sum(input) - fee`
- Withdraw amount is `sum(output) + fee`

**Comment by yihuang** [comment]
We can also support query history staking state if that can solve your problem.

**Comment by yihuang** [comment]
It's good to have a common event type to cover all the potential staking state changes:
event type: StakingChanges
event value:
- staking diff: `Vec<(field, diff of value)>`
- reason: rewarding | slashing | tx...

**Comment by calvinaco** [comment]
I am claiming this issue
