### ISSUE TITLE
Problem: Performance of merkle library is not clear

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1436]
Benchmark metrics:
- tps
- number of internal nodes
- disk usage

**Comment by tomtau** [comment]
the time of different operations (insert, update, delete, get/lookup with proof) should ideally be also checked in different settings -- e.g. against empty tree in-memory or tree with 100,000s of nodes on-disk

**Comment by yihuang** [comment]
Currently, delete is not supported, and update should be similar to insert, so didn't separate the update from insert yet.
