### ISSUE TITLE
Problem: tx-history not correctly restored after restoration

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1456]
after hdwallet restoration, tx-history is not fully recovered.
Outgoing tx is marked as Incoming.
tx is not recorded to wallet state in processing with memento pattern

solution would be , in doing memento pattern,
write "tx" right away to wallet state.
so txs which reference that tx as utxo input, will work correctly.

**Comment by leejw51crypto** [comment]
this is found in processing of "address auto recovery" of bip44 
modified.
tidying up now

**Comment by tomtau** [comment]
fixed in #1396
