### ISSUE TITLE
Problem: no choice of merkletrie

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1463]
currently, merkletrie is hard coded.
i suggest mutiple merkletrie methods as a runtime option

make a general trait for merkletrie, as we did for storage.
for merkletrie, 
1. starling
2. jellyfish

so, when user needs very fast merkletrie, user can choose specific merkletrie, like embedded db options.

**Comment by tomtau** [comment]
this is a non-goal -- there needs to be a consensus on the computed app hash. If 34+% of validators choose a different trie at runtime, there's a chain halt or they won't be able to start up due to genesis integrity mismatch
