### ISSUE TITLE
Problem: client-rpc process is not necessary for python integration tests

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1483]
With the new RPC style c API, python integration tests can run by calling the c API directly, no need the client-RPC process.
- Better testing the API
- Showcase multi-linguist client implementation.

If this approach proved to be successful, maybe we don't need to maintain client-rpc at all?

**Comment by tomtau** [comment]
potentially, it can also decrease the number of dependencies.

there are a few external places where client-rpc is used e.g. https://github.com/crypto-com/sample-chain-wallet (there I guess it'll make sense to replace it with the Node.JS library)
and I think @calvinaco has written a few internal bash scripts that `curl` client-rpc...
not sure if any external parties on the testnet are using client-rpc -- @lezzokafka ?
anyway, if we ever decide to deprecate it, it should be graceful.

**Comment by lezzokafka** [comment]
> not sure if any external parties on the testnet are using client-rpc -- @lezzokafka ?

Not that I know of. I think most of the external parties are using client-cli to perform node-join and staking related operations @tomtau.

**Comment by leejw51crypto** [comment]
like ethereum, geth  has cli + interactive+ rpc.
maybe we can consider similar approach.
combine cli+ rpc together

but rpc via http is still useful and valid using with other languages.
because it's by tcp level.

**Comment by yihuang** [comment]
- Drop the jsonrpc dependency, but keep the RPC schema deriving stuff, probably cherrypick the related code from jsonrpc library.
- Write a simple HTTP server process incoming requests one by one, since the current APIs are not supposed to be called concurrently.
