### ISSUE TITLE
Problem: too tight coupling with tendermint-rs

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1509]
tendermint-rs shoud be 100% accurate with the tendermint.
any minor unexpected token in the packet can break the flow.

but we don't have 100% gurantee for this

how about catch that error, ( serde-json converting fail)
if that happens , do like below
1. extract value that is crucial
2. proceed
3. make a warning to log , to upgrade tendermint-rs

this is for future stability issue.
we can buy sometime to correct tendermint-rs

**Comment by yihuang** [comment]
This might involves many redundant work.

**Comment by tomtau** [comment]
I don't understand the problem here -- is it "too tight coupling with tendermint-rs"?

**Comment by leejw51crypto** [comment]
yes, maintaining tenderint-rs well is the better solution
so i close this issue
