### ISSUE TITLE
Problem: v0.5.x client-cli cannot sync

### ISSUE THREAD

**Issue by calvinlauco** [crypto-com/chain#1552]
**Describe the bug**
When trying to sync a wallet with client v0.5.x (including master), the client-cli returns with
```
Error: Initialization error: Unable to initialize sled storage at path: .storage
```

**To Reproduce**
1. Build on release or master branch
2. Create/restore a wallet
3. Run `./client-cli sync --name Wallet`

**Expected behavior**
Expected the synchronization should start working

**Screenshots**
![image](https://user-images.githubusercontent.com/16665951/81209029-85f54700-9002-11ea-8cdd-14de0cf5039d.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Ubuntu 18.04
 - Version: v0.5.x, master

**Comment by lezzokafka** [comment]
Note: v0.4 release works fine.
