### ISSUE TITLE
Problem: client-cli isn't continuously tested

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1555]
in order to discover bugs like https://github.com/crypto-com/chain/issues/1552 early,
it'll be good to at least run some basic functionality in integration tests (e.g. from scratch / no storage, sync with client-cli and after it's finished, use client-rpc to cross-check the result)

**Comment by tomtau** [comment]
Does "pipe" work for inputting (interactive) inputs to client-cli?

**Comment by yihuang** [comment]
> Does "pipe" work for inputting (interactive) inputs to client-cli?

I think it works.
