### ISSUE TITLE
Problem: one cannot optionally disable light client verification

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1611]
above env is crucial for client-rpc
so make it not optional , in client-rpc

also display how, to generate it in help

**Comment by tomtau** [comment]
Isn't there an option to disable verification in client-*? In that case, one doesn't need the genesis hash?

**Comment by yihuang** [comment]
> Isn't there an option to disable verification in client-*? In that case, one doesn't need the genesis hash?

Currently no such option, only a more specific one to `--disable-fast-forward`.

**Comment by leejw51crypto** [comment]
how about?
--disable-check-hash

**Comment by tomtau** [comment]
I renamed it as:
> Problem: one cannot optionally disable light client verification

It'd disable the genesis hash check + light client checks (I guess one could do that if they run their own full node and trust it)

**Comment by tomtau** [comment]
I also opened this issue: https://github.com/crypto-com/chain-docs/issues/143

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
working on it

**Comment by leejw51crypto** [comment]
options would be
--disable-light-client-verification

**Comment by leejw51crypto** [comment]
modified   get_genesis_sync_state

**Comment by yihuang** [comment]
> modified get_genesis_sync_state

The entry point light client verify logic is here: https://github.com/crypto-com/chain/blob/master/client-core/src/wallet/syncer.rs#L432

**Comment by leejw51crypto** [comment]
integration test done,
checking code now

**Comment by leejw51crypto** [comment]
in code review
