### ISSUE TITLE
Problem: outgoing wallet deposit amount is not displayed 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#1614]
**To Reproduce**
1. Send a deposit transaction to a staking address;
2. Check the history via client-cli or rpc;
3. The Deposit transaction is recorded, but the amount is zero. 

**Expected behavior**
- The deposit amount should be displayed

**Screenshots**

<img width="734" alt="Screen Shot 2020-05-19 at 11 37 47 am" src="https://user-images.githubusercontent.com/51898510/82281942-39781700-99c5-11ea-9c50-3e7f40cb1f17.png">

**Comment by tomtau** [comment]
is it to the staking address in the same wallet or external?

**Comment by leejw51crypto** [comment]
it's staking address which belongs to the wallet which user owned

**Comment by tomtau** [comment]
> it's staking address which belongs to user's wallet

I think in that case, the display is "correct" -- the history display is currently showing "in/out wallet"... so if it goes from the same wallet to the same wallet, the amount is 0 ?

**Comment by lezzokafka** [comment]
Same wallet => same wallet:

**Comment by leejw51crypto** [comment]
for example, if we deposit to other staking account, which doesn't belong to my wallet.
check txin, display that deposit tx, with amount

**Comment by lezzokafka** [comment]
For example, if you would like to deposit  1000 CRO from Waller `W` to a staking address `S` the current approach is the following: 
- Step 1) Create a transaction with 1000 CRO to "yourself" and get the UTXO;
- Step 2) Finish the deposit by spending the UXTO from the last step. 

Currently, If `S` is in the wallet `W`, you will see
- an outgoing "Transfer" transaction with value "0;
- an outgoing "Deposit" transaction with value "0".

If `S` is not in the wallet `W`:
- an outgoing "Transfer" transaction with value "0" only.

**Comment by tomtau** [comment]
for the second case (`S` is not in the wallet `W`), it doesn't show "Deposit" with value X (what's being deposited) at the moment
