### ISSUE TITLE
Problem: keypackage not verified in nodejointx / council node data

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1616]
- (disabled in mock mode)
- tx validation should check that cert field in `ConfidentialInit` is a valid keypackage
- (it can also extract the security version number (ISVSVN) -- if the number is greater than the existing one it has from genesis / previously, it can display a warning)
- some basic TDBE runner that will generate keypackage + expose it somehow (dump to TCP? or just printout? custom stream?)
- client/tool support for fetching the keypackage for node join tx construction + preparation of genesis
(+ integration test modifications)

**Comment by yihuang** [comment]
The `ConfidentialInit` is not accurate since the keypackage in `StakedState::Validator::CouncilNode` can also be updated?
How about simply rename to `keypackage`, and store `KeyPackage` directly?

**Comment by tomtau** [comment]
> The `ConfidentialInit` is not accurate since the keypackage in `StakedState::Validator::CouncilNode` can also be updated?
> How about simply rename to `keypackage`, and store `KeyPackage` directly?

do you mean to rename `cert` to `keypackage` or renaming `ConfidentialInit`?
I think the former is fine, as the TX wire format won't change (genesis will break, but it's already had a breaking change on the current master anyway)

**Comment by yihuang** [comment]
> > The `ConfidentialInit` is not accurate since the keypackage in `StakedState::Validator::CouncilNode` can also be updated?
> > How about simply rename to `keypackage`, and store `KeyPackage` directly?
> 
> do you mean to rename `cert` to `keypackage` or renaming `ConfidentialInit`?
> I think the former is fine, as the TX wire format won't change (genesis will break, but it's already had a breaking change on the current master anyway)

I was trying to rename `ConfidentialInit`, but I guess rename `cert` to `keypackage` is good enough?

**Comment by tomtau** [comment]
> 
> I was trying to rename `ConfidentialInit`, but I guess rename `cert` to `keypackage` is good enough?

changing `ConfidentialInit` to `KeyPackage` would break the tx wire format -- this single `keypackage` field is ok

**Comment by yihuang** [comment]
> - (it can also extract the security version number (ISVSVN) -- if the number is greater than the existing one it has from genesis / previously, it can display a warning)

Is it to warn that when a new version of enclave is appeared?

**Comment by tomtau** [comment]
> Is it to warn that a new version of enclave is appeared?

Yes, it's to signal security upgrades -- more logic around that will be needed, but this is just for the start
