### ISSUE TITLE
Problem: Can't deposit into other's new staking address

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1621]
The intension of the restriction is to prevent wrong deposit tx, but it also block valid cases.

Options:
- remove the restriction
- add confirmation in client ui
- whitelist the operator

Decision: Option2
- Remove the restriction from client network ops
- add a check and double confirmation in client-cli.

**Comment by lezzokafka** [comment]
Quick comment:  I think whitelisting the address might works better.

**Comment by leejw51crypto** [comment]
what's white list scenario?

**Comment by calvinlauco** [comment]
> what's white list scenario?
> 
> 
> 
> how about option2
> 
> add confirmation?
> 
> "that address doesn't belong to your wallet?, will you proceed to deposit?"

Yes, a double confirmation seems good. Which scenario you find whitelisting works better?

**Comment by tomtau** [comment]
> what's white list scenario?
> 

I think it's like that the client/wallet can maintain an "address book" of whitelisted addresses it's ok to deposit to. It's however a more complex change -- e.g. it'd be more difficult to make it "backwards-compatible" (as it may change the storage schema)... so if we want this to cherry-pick to 0.5, the whitelist would need to be somehow optional / be able to convert from the old format.

Anyway, I guess option 2 is the simplest? @yihuang @leejw51crypto is any of you already working on a fix?

**Comment by yihuang** [comment]
> > what's white list scenario?
> 
> I think it's like that the client/wallet can maintain an "address book" of whitelisted addresses it's ok to deposit to. It's however a more complex change -- e.g. it'd be more difficult to make it "backwards-compatible" (as it may change the storage schema)... so if we want this to cherry-pick to 0.5, the whitelist would need to be somehow optional / be able to convert from the old format.
> 
> Anyway, I guess option 2 is the simplest? @yihuang @leejw51crypto is any of you already working on a fix?

I can work on this today.

**Comment by lezzokafka** [comment]
Oh, sure. I am happy with the double confirmation as well
