### ISSUE TITLE
Prolblem: no documentation for unbonding period

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1641]
unbonding is now simplified to tendermint evidence duration.
add these to the documentation.

and also 
duration unit is 10^9 seconds (nano seconds)
give some example to user,too

**Comment by tomtau** [comment]
maybe better to be opened in chain-docs?

**Comment by lezzokafka** [comment]
@leejw51crypto I moved it to chain-docs[#144](https://github.com/crypto-com/chain-docs/issues/144).
