### ISSUE TITLE
Problem: no graceful close in client-cli after sync

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1649]
E[2020-05-22|15:52:14.037] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:39560 err="websocket: close 1006 (abnormal closure): unexpected EOF"
E[2020-05-22|15:52:14.037] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:39572 err="websocket: close 1006 (abnormal closure): unexpected EOF"

before finishing sync, graceful close websocket,
also check with client-rpc, too

**Comment by tomtau** [comment]
btw there was this older issue: https://github.com/crypto-com/chain/issues/808

**Comment by leejw51crypto** [comment]
ok, i'll fix this issue

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
sync now "doing graceful close" by sending "Close" message via websocket 
before closing.

today , tidy up the code, some refactoring

**Comment by leejw51crypto** [comment]
in code-review

used Drop to send `close message` via websocket
