### ISSUE TITLE
Problem: transfer coin failed using client-cli

### ISSUE THREAD

**Issue by linfeng-crypto** [crypto-com/chain#1657]
can not transfer coin to other wallets' address using client-cli:
1. after making a transfer tx, the balance in the sender's wallet is pending
2. sync the sender's wallet, still pending
3. after a few minutes(50 blocks), sync again,  pending rollback.
4. The receiver can not get the coin.

**Comment by leejw51crypto** [comment]
i checked, but i cannot revive it.
maybe viewkey error?

**Comment by leejw51crypto** [comment]
i'll check the issue

**Comment by linfeng-crypto** [comment]
or the receiver can get the coin, but the sender's coin not change, if you send again, the error will be:

```
Tendermint RPC error: enclave tx validation failed: transaction spends an input that was already spent
```

**Comment by tomtau** [comment]
potentially fast-forward issue
