### ISSUE TITLE
Problem: ambiguous error message in check_genesis_hash

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1670]
"genesis app hash from tendermint {} is not match setted genesis hash {}"
is ambiguous
it should
"genesis hash from tendermint {} is not match setted genesis hash {}"

we can summarize terms
genesis hash: hash of the genesis
app hash: hash of app_state in genesis

also check in both
client-cli, client-rpc
to display correct error message when "genesis hash" doesn't match from the tendermint

**Comment by tomtau** [comment]
@leejw51crypto https://github.com/crypto-com/chain-docs/issues/143 @lezzokafka is now updating the docs -- he may change the term "genesis hash" to something not to be confused with the app hash in genesis ("trusted anchor hash"? https://docs.tendermint.com/master/tendermint-core/light-client-protocol.html ), which could also help

**Comment by lezzokafka** [comment]
After a discussion with @linfeng-crypto, 
maybe we can name it with something like trusted-anchor "fingerprint"
so that it is not confused with any other hashes?

**Comment by leejw51crypto** [comment]
not bad

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
replace with "genesis fingerprint"
