### ISSUE TITLE
Problem: no instructions for compiling chain-core to WASM

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1690]
secp256k1 (BCH version) in WASM: https://github.com/bitauth/bitcoin-ts using emscripten https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

**Comment by tomtau** [comment]
perhaps one will need something like cro-clib https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm with some functions exposed via `wasm_bindgen`

**Comment by leejw51crypto** [comment]
i'll look into it

**Comment by leejw51crypto** [comment]
started
1. write  simple hello world via WASM
2. apply to chain_core

rough ideas is to build tx and broadcast with pure html5 X ecma javascript
(with utxo data which can required before-hand)

**Comment by leejw51crypto** [comment]
working with emcc, trying to compile secp256k1

**Comment by leejw51crypto** [comment]
done, writing document, and will submit pr
