### ISSUE TITLE
Problem: no gen package command in dev-utils

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1692]
currently , only in client-cli,
add to dev-utils 
use the same command with client-cli

**Comment by tomtau** [comment]
@leejw51crypto or it can be moved from client-cli. it's a more of a developer / temporary command.
client-cli can just have a just input to accept the base64-encoded payload

**Comment by leejw51crypto** [comment]
ok, i'll move the code from client-cli
started this issue

**Comment by leejw51crypto** [comment]
made keypackage correctly, now trying to run the chain

**Comment by leejw51crypto** [comment]
working on it

**Comment by leejw51crypto** [comment]
done, submitted pr

**Comment by leejw51crypto** [comment]
in code-review
