### ISSUE TITLE
Problem: no compression for keypackage

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1698]
keypackage is un-compress binary data, it can be 1/3 size of original roughly.
so 
serialize -> compress -> base64 encoding

recommend zlib for this, but other compression lib would be fine

also write directly that data from mls.sgxs, not raw binary

**Comment by tomtau** [comment]
Is this a problem?
for it being in genesis.json, the genesis.json can just be gzipped.
for it being in node join tx -- that doesn't happen often and still fits the max TX size limit

**Comment by leejw51crypto** [comment]
yes, not a problem,  an enhancement.
because it's quite large in genesis.json
