### ISSUE TITLE
Problem: reading genesis time from tendermint make `dev init` fail

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1705]
genesis time should be later then creation time of keypackage.
so in dev-utils

1. don't read genesis time from tendermint
2. instead set it with keypackage time

./dev-utils genesis generate --genesis_dev_config_path  ./dev.json
```
thread 'main' panicked at 'distribution validation error: KeyPackageVerifyError(NotBefore(1591152931))', chain-abci/src/app/app_init.rs:231:17

```

**Comment by yihuang** [comment]
We need to configure tendermint genesis file(genesis time, max evidence age, etc.) rather then just use the default one generated by `tendermint init`.

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
working

**Comment by leejw51crypto** [comment]
done
now tidying up
