### ISSUE TITLE
Problem: no domain separation of hashed data types

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1715]
To prevent hash collisions between different data types, we can use unique data type names as salt, we can use macros to minimize boilerplates code.
Could extract from https://github.com/libra/libra/blob/master/crypto/crypto/src/hash.rs, a pre-step to vendor the jellyfish merkle tree?

The usage would be like this for us:
```rust
use chain_crypto::CryptoHash;
use chain_crypto_derive::{AsRefCryptoHash, CryptoHasher, PSCCryptoHash};
use parity_scale_codec::Encode;

#[derive(Encode, CryptoHasher, PSCCryptoHash)]
struct Test1 {
    a: String,
}

#[derive(Encode, CryptoHasher, PSCCryptoHash)]
struct Test2 {
    a: String,
}

#[derive(CryptoHasher, AsRefCryptoHash)]
struct PublicKey([u8; 32]);
impl AsRef<[u8]> for PublicKey {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

#[derive(CryptoHasher, AsRefCryptoHash)]
struct PrivateKey([u8; 32]);
impl AsRef<[u8]> for PrivateKey {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

fn main() {
    let t1 = Test1 {
        a: "test".to_owned(),
    };
    let t2 = Test2 {
        a: "test".to_owned(),
    };
    assert_ne!(t1.hash(), t2.hash());

    let k1 = PublicKey([1_u8; 32]);
    let k2 = PrivateKey([1_u8; 32]);
    assert_ne!(k1.hash(), k2.hash());
}
```

Implemented with custom prefixes or `blake3::derive_key` is implementation detail, should be trivial to switch either way.

**Comment by tomtau** [comment]
@yihuang is this for domain separation inside jellyfish merkle (or among different jellyfish merkle trees)?
It seems for Libra, it was considered to use cSHAKE -- which seems to provide similar hash with customising string as https://docs.rs/blake3/0.3.4/blake3/fn.derive_key.html ?

**Comment by yihuang** [comment]
I think we want domain separation across the whole project, also prefixed with the project name?

**Comment by tomtau** [comment]
> I think we want domain separation across the whole project, also prefixed with the project name?

do you mean tx-id computation, extended addresses etc.? that breaks transaction wire format, i.e. all external software developed and being developed on 0.5

**Comment by tomtau** [comment]
separating out new things or parts that weren't promised to be "stable" is ok; breaking everything not ok.

**Comment by yihuang** [comment]
> > I think we want domain separation across the whole project, also prefixed with the project name?
> 
> do you mean tx-id computation, extended addresses etc.? that breaks transaction wire format, i.e. all external software developed and being developed on 0.5

I guess we can also limit it within merkle tree, or only any new stuff in the future if cost of breaking backward compatibility is big.

**Comment by tomtau** [comment]
Some hashing parts that are expected to be broken, so can add some domain separation (if they don't have something already):
- app hash
- app hash components
- genesis fingerprinting
- enclave protocols

**Comment by tomtau** [comment]
may be worth "breaking" txids:
> that an attacker sends a prefix for [TX-A][payload-TX-B]. where TX-A can TX-B have the same structure.
> we show it as TX-A (because of the prefix) but actually the user signs something that later is wrapped as TX-B
> I wonder if it would make sense to include the type prefix in the hash too

**Comment by yihuang** [comment]
There's some work to port libra's crypto crate: https://github.com/yihuang/chain/tree/cryptohash
