### ISSUE TITLE
Problem: no option for keypackage in client-cli, join-tx generation

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1775]
because, keypackage is not short, in terminal environment, copy & paste not working correctly sometimes.

so, in client-cli add option
--keypackage key.txt
if option is given, read the file  , otherwise, ask of the user like now.

**Comment by tomtau** [comment]
or binary file?

**Comment by tomtau** [comment]
after parsing the file with keypackage, it can also display its info in human form (expiration time in local timezone, pubkey in hex or base64, ...)
