### ISSUE TITLE
Problem: possible panic of operations in mls modules

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1784]
As TDBE will use the mls library as its part when processing data obtained from the light client, it shouldn't crash e.g. from malformed encryption etc.

**Comment by tomtau** [comment]
@devashishdxt fyi, one other point raised on that call today -- besides eliminating unwraps, it'd be good to separate out library API logically, so it is clearer what's internal and its invariant is that the inputs already were validated for certain properties, versus external

**Comment by tomtau** [comment]
e.g. something similar what's done with https://docs.rs/untrusted/0.7.1/untrusted/ and parsing in rustls

**Comment by tomtau** [comment]
altogether with this or #1785 #1786 #1787 #1788, it'd be good to increase code coverage of the mls module -- e.g. add negative test cases for the possible error types

**Comment by yihuang** [comment]
- Sign proposals
  - `get_signed_add`
  - `get_signed_remove`
  - `get_signed_self_update`
- commit proposals
  - `init_commit`
  - `commit_proposals`
- `process_commit`
- `init_group_from_welcome`

These are the public facing APIs directly get external input.
