### ISSUE TITLE
Problem: unnecessary `mock` function argument in cro-clib

### ISSUE THREAD

**Issue by linfeng-crypto** [crypto-com/chain#1792]
Solution: use `mock-enclave` feature instead of `mock` function agument  in cro-lib

`mock` is used for development but should be kept away from the release binary.

https://github.com/crypto-com/chain/blob/master/cro-clib/src/jsonrpc.rs#L267

**Comment by leejw51crypto** [comment]
started

**Comment by tomtau** [comment]
print warning if mock is used?

**Comment by tomtau** [comment]
restrictions to stop mock client from connecting to the real implementation

**Comment by leejw51crypto** [comment]
ok

**Comment by tomtau** [comment]
from the call discussions, this may just be a deletion of dead code

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
in code-review
