### ISSUE TITLE
Problem: Outgoing deposit history is not displayed

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#1798]
After testing locally with @linfeng-crypto, we found a similar issue as #1614: 

**To Reproduce**
1. Send a deposit transaction to a staking address that belongs to another wallet;
2. Check the history via client-cli or rpc;
3. The deposit transaction is not recorded.

**Expected behavior**
- Deposit history should be displayed.

**Comment by tomtau** [comment]
may be changing sync to check with spent utxos can fix this

**Comment by linfeng-crypto** [comment]
#1978

**Comment by linfeng-crypto** [comment]
#1908
