### ISSUE TITLE
Problem: Ambiguous message while importing an existing transaction 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#1801]
**To Reproduce**
1. Import a transaction from the given plain transaction data;
2. Import amount is being shown ;
3. Repeat step 1;
4. Import amount is being shown again.

**Expected behavior**
- If the tx is already imported, show message "_This transaction is already imported/in your wallet_" etc.

**Screenshots**

![Screen Shot 2020-06-22 at 8 43 17 pm](https://user-images.githubusercontent.com/51898510/85353129-231c2880-b53a-11ea-825b-b8d97da1b1f3.png)

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done, now testing

**Comment by leejw51crypto** [comment]
in code-review
