### ISSUE TITLE
Problem: frequent corrupt .storage of client-rpc

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1808]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Initialization error: Unable to initialize sled storage at path: .storage
 => IO error: could not acquire lock on "/$HOME/.storage/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', client-rpc/server/src/program.rs:87:5

1. make global mutex to avoid concurrent running of client-cli, client-rpc
2. kill program and re-run, check .storage is secure
3. consider sled db-level protection such as journaling

**Comment by tomtau** [comment]
@leejw51crypto how could this be reproduced? if you try to run multiple processes at the same time? I think it's expected -- and sled already has this global lock (and it does journalling).
or do you mean if the program crashes and the lock is not removed? what is this problem precisely?

**Comment by leejw51crypto** [comment]
just run, client-cli, client-rpc while client-rpc is on
(forgot client-rpc is running)
program exit with error message, but next time, when i try to run again.

cannot run again with above message

**Comment by tomtau** [comment]
@leejw51crypto seems that's normal / expected (you can't have more than 1 OS process accessing the embedded DB)? so what is the problem? that the error/panic message is confusing?

**Comment by leejw51crypto** [comment]
error is ok, but cannot use .storage at all,
cannot run client-rpc again

i think some file lock is abandoned by some reason.

**Comment by tomtau** [comment]
@leejw51crypto did the client-rpc crash and leave the lock?

**Comment by tomtau** [comment]
or did you kill the process non-gracefully?

**Comment by leejw51crypto** [comment]
not gracefully, killall client-rpc

**Comment by tomtau** [comment]
@leejw51crypto if it's not reproducible... isn't it that you just had client-rpc running?
sled seems to use the normal OS file locking mechanism underneath (e.g. `flock` on Linux)

**Comment by leejw51crypto** [comment]
i found the pattern,
while client-rpc is on, i removed the .storage, then that error appears

**Comment by leejw51crypto** [comment]
because it's not reproduceable, i'll close this issue.
