### ISSUE TITLE
Problem: no single runner for chain

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1817]
running chain needs a script, because there are several files to setup.
## why
so make a single runner like supervisor
features are like this

1. run all subprograms - including tendermint
2. when main finishes, also finish all sub-programs
3. also write log to separate folder in /logs/abci/ , logs/tx-query,  so that user can see log easily
4. use json or yaml script to setup
5. it should be easy to run and modify

## how to implement
1. use RUST child process creation api, so that, automatically shutdown child programs
2. maybe we can use `chain` for binary file name
3. for default mode, it just runs with test-net peers, which is also setup with test-node as peer

**Comment by tomtau** [comment]
already done with https://github.com/crypto-com/chain/blob/master/integration-tests/bot/chainbot.py#L222
