### ISSUE TITLE
Problem: no convenient to see logs

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1818]
currently, logs are just text files, hard to see and view.
add sqlite logs as an option, so user can see log easily.
there are many log viewers for sqlite.

also sqlite is multi-process ready, it would be handy to see current status.

**Comment by tomtau** [comment]
@leejw51crypto what's the problem ("hard to see and view") about logs in text files?
one can open them in any text editor, or just use `less <...>.log` to view them? plus one has all the text processing tooling (`awk`, `sort`, `grep`, ...) ready for them?

**Comment by leejw51crypto** [comment]
ok, in cosole , plain log would be eaiser
so  i close this issue.
