### ISSUE TITLE
Problem: `chain-storage` dependency in clients

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1832]
chain-storge is only necessary for abci core.

rocksdb need c++ library,
so client-side only needs c-language sdk for compatiblity.
also rockdb is very big to include it in wasm, too.

it would be much handier to support `cro-clib` as clibrary (small and compact),
because c-lib has a wide range of compatibilities.

so i suggest as below.

1. make chain-storage only used in abci
2. remove dependency to chain-storage in
client-core,
client-network,
not in any client-side
3. if possible, decouple jelly-fish and kv-rocksdb , and make it feature-guarded, can use sled ,too.

**Comment by tomtau** [comment]
@leejw51crypto I guess the "chain-storage" is imported for the light client verification (verifying merkle proofs returned from jelly-fish)? but yes, it'd be good to decouple that part

**Comment by yihuang** [comment]
can make the kvdb-rocksdb optional, most of the code work with kvdb traits, only a constructor reference rocksdb directly.

**Comment by leejw51crypto** [comment]
yes, that would be good
