### ISSUE TITLE
Problem: outdated c-binding example 

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1845]
1. modify example to run in latest master
2. check sync example working

**Comment by leejw51crypto** [comment]
working on it

**Comment by tomtau** [comment]
are Java/Swift samples also affected?

**Comment by leejw51crypto** [comment]
yes, need to modify
1. sync protocol- adding sync option
2. hdwallet creation- mnemonic count

**Comment by tomtau** [comment]
seems this was resolved
