### ISSUE TITLE
Problem: client-cli does not sync Transfer transactions correctly

### ISSUE THREAD

**Issue by calvinlauco** [crypto-com/chain#1862]
**Describe the bug**
After sending a Transfer transaction, the transaction goes through but the balance and history are not updated

**To Reproduce**
1. Setup a Devnet using the `Makefile`
2. Withdraw the funds and do a transfer to an address of another wallet
3. Do `$ client-cli sync ...`
4. Check for balance and history

**Expected behavior**
The balance should be deducted and the history should show the Transfer transaction

**Screenshots**

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Not Applicable
 - Version: master(https://github.com/crypto-com/chain/commit/cff92294d4ca4b107f3d087cdb30ef5ac47d9409)

**Comment by yihuang** [comment]
is there pending in balance result?

**Comment by calvinlauco** [comment]
> is there pending in balance result?

Yes

After you mentioned this one, it recalled me about the old issue of disabling fast forward. So I did a quick try with disabling the fast sync and it is ok now. I will update it in the https://github.com/crypto-com/chain-docs

**Comment by calvinlauco** [comment]
A quick question: will this one be solved in the near future?

**Comment by calvinlauco** [comment]
Referencing the issue here: https://github.com/crypto-com/chain/issues/794
