### ISSUE TITLE
Problem: still infeasible to create a large chunk of transfer addresses in HD wallet in client-*

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1875]
observed by @calvinaco when redoing the exchange-like setup stress tests.
ref: https://github.com/crypto-com/chain/issues/1233
according to @leejw51crypto it's due to all them being in memory and time spent on copying -- no numbers / experiments done though

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
done, will submit pr
