### ISSUE TITLE
Problem: Fortanix is not supporting the latest SGX DCAP deriver: "SGX device was not found, Is a directory"

### ISSUE THREAD

**Issue by calvinlauco** [crypto-com/chain#1952]
According to https://github.com/fortanix/rust-sgx/issues/247

fortanix does not support DCAP driver after v1.32 until it is merged to upstream drivers. This would affect the Azure VMs because they have been updated their driver just recently.

When running our latest chain on machines having the new DCAP driver, `tx-query` will return error
```
thread 'main' panicked at 'SGX device was not found: Os { code: 21, kind: Other, message: "Is a directory" }', chain-tx-enclave-next/tx-query-next/app-runner/src/main.rs:93:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This issue is opened to keep track of this issue.

Reference:
https://github.com/fortanix/rust-sgx/issues/247
https://edp.fortanix.com/docs/api/src/sgxs_loaders/isgx/mod.rs.html#229

**Comment by tomtau** [comment]
@calvinaco we only just IAS in the current code -- https://github.com/crypto-com/chain/issues/1777
why a dcap driver? one can just install the normal driver: https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/ ?
