### ISSUE TITLE
Problem: light client trusted block can't be set in client-*

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#2005]
this could be a bit partially automated, as @yihuang pointed on Slack:
> I think in real life, when have trusting period issue, we might just prompt user a warning, get a double confirmation, and proceed by trusting whatever new block.

I guess the prompt should display the block hash and ask the user to verify it e.g. in a block explorer

**Comment by tomtau** [comment]
@yihuang I split up this issue:
https://github.com/crypto-com/chain/issues/2009
https://github.com/crypto-com/chain/issues/2011

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
started,
working sub-issues first
adding peer, witness to light-client

**Comment by leejw51crypto** [comment]
coded, tidy up,

now testing

**Comment by leejw51crypto** [comment]
start issue 2005

**Comment by leejw51crypto** [comment]
now working in client-rpc, client-cli

**Comment by leejw51crypto** [comment]
done,
checking integration test

**Comment by leejw51crypto** [comment]
submitted pr
