### ISSUE TITLE
Problem: no detail for light client error message

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#2006]
in dev.json
evidence, max_age_num_blocks is 10,
this error occurs in client-rpc sync
```
Verify error:
     => Error(Context { kind: NoWitnessLeft, source: None, backtrace: Some(   0: tendermint_light_client::peer_list::PeerList<T>::replace_faulty_primary
```

add detail information about the error which caused `replace_faulty_primary`

**Comment by yihuang** [comment]
probably need to be solved in tendermint-rs side:
https://github.com/informalsystems/tendermint-rs/blob/master/light-client/src/supervisor.rs#L257

**Comment by yihuang** [comment]
https://github.com/informalsystems/tendermint-rs/pull/477
