### ISSUE TITLE
Problem: light client PeerId can't be configured in client-*

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#2009]
one PeerId may have multiple addresses AFAIK - @yihuang ?

**Comment by yihuang** [comment]
one PeerId might change ip/domain addresses I guess?

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
A single peer ID can have multiple IP addresses associated with it, but a node will only ever connect to one at a time.

https://docs.tendermint.com/master/spec/p2p/peer.html

**Comment by leejw51crypto** [comment]
adding option

**Comment by leejw51crypto** [comment]
in code-review

**Comment by tomtau** [comment]
fixed in https://github.com/crypto-com/chain/pull/2068
