### ISSUE TITLE
Problem: light client witness nodes can't be configured in client-*

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#2011]
I guess in the old terminology, it used to be called "backup full node" -- @yihuang https://github.com/informalsystems/tendermint-rs/blob/master/docs/architecture/adr-003-light-client-core-verification.md#context ?

**Comment by tomtau** [comment]
maybe multiple nodes read from a config file

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
in code-review
