### ISSUE TITLE
Problem: optimize WalletState

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#2031]
modify_wallet_state is called in handle_batch, which is called 2 times per block , in sync
in normal case, it would be OK, but in there is billions of utxos,
because it read and writes whole `WalletState` as one record.
it may slow down overall sync speed

1. preserve current methods in WalletState
2. in apply memento, it writes to DB like now
3. in reading utxos and pending utxos, it reads from the DB

after this pr , these are results
1. sync will be faster , because don't write the same utxo to the DB  for each block
2. because it will directly refer to DB, memory consumption will be reduced

**Comment by tomtau** [comment]
doesn't seem relevant -- https://www.blockchain.com/charts/utxo-count
maximum number of utxos of the _whole network_ (i.e. each individual wallet won't need to worry about even millions) running for over 10 years has been around 70 million
