### ISSUE TITLE
Problem: indirect communication between tx-validation and tx-query

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#2051]
can open unix-domain socket -- expose via usercallextension to both tx-validation (TVE) and tx-query (TQE) enclaves.
TVE / TQE code for TLS can reuse the implemented enclave-to-enclave comms from TDBE, but needs a change that MRENCLAVE measurement of TQE is a compile-time parameter for TVE https://github.com/crypto-com/chain-docs/blob/master/docs/modules/tdbe.md#svn-verification--compilation-order

TQE->chain-abci: for fetching / decrypting, it can have "read only storage" direct requests to chain-abci / usercall extension with some request-reply buffer

**Comment by leejw51crypto** [comment]
started

**Comment by tomtau** [comment]
@leejw51crypto @devashishdxt is now working on https://github.com/crypto-com/chain/issues/1994 which has some overlap/similarity with this issue (attested TLS, compile-time MRENCLAVE and checking measurements, unix socket pair passed via `UsercallExtension` methods...), so you can sync up for any common intermediate PRs (e.g. changes to the build process)

**Comment by leejw51crypto** [comment]
ok, i'll refer to #1994 pr,
using common code-base already done

**Comment by leejw51crypto** [comment]
start coding , basic unix socket first

**Comment by leejw51crypto** [comment]
made communication structure, and protocol
now working on replace current code


tx_query -> abci : call tx-validation here..    
========>
tx_query->abci : read storage prepare tx
tx_query->tx_validation: encrypt

**Comment by tomtau** [comment]
discussed with @leejw51crypto on slack -- it may not be worth putting a direct communication channel between TQE and TVE right now, as it still needs a storage access (for looking up staked state and sealed transactions from chain-abci).

The code written so far can still be reused/repurposed for:
https://github.com/crypto-com/chain/issues/1994
