### ISSUE TITLE
Problem: client-rpc panic without specify option --light-client-peers

### ISSUE THREAD

**Issue by allthatjazzleo** [crypto-com/chain#2094]
```bash
Network type Devnet id AB
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid input: there is no light-client peers.
specify at least two peers, use light-client-peers option', client-rpc/server/src/program.rs:103:5
```
Should add --light-client-peers to have temporary fix in Makefile until it is solved in #2090

Also, `set-genesis-fingerprint` target in Makefile rely on libzmq3-dev installed to compute genesis-fingerprint.

**Comment by tomtau** [comment]
the solution is simple by resolving this issue: https://github.com/crypto-com/chain/issues/2090 -- no need to add extra workaround to the makefile if this can be solved directly
