### ISSUE TITLE
Problem: dynamically set CRYPTO_GENESIS_FINGERPRINT requires libzmq3-dev installed

### ISSUE THREAD

**Issue by allthatjazzleo** [crypto-com/chain#2102]
Makefile use dev-utils to compute and set CRYPTO_GENESIS_FINGERPRINT dynamically for client-rpc.
Got this error if user's machine didn't install libzmq3-dev beforehand
```
./target/debug/dev-utils: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
CRYPTO_GENESIS_FINGERPRINT =
```
Should install libzmq3-dev in Makefile if not installed

**Comment by tomtau** [comment]
@allthatjazzleo not sure if that's necessary / intended -- for testnet, it should be fixed, so dynamically setting it and ignoring the fixed value could hide problems / unintentional code breaking.
for devnet, I'm not sure

**Comment by allthatjazzleo** [comment]
For testnet, we should stick to fixed one.
But for devnet, as we have frequent update in code which cause different `CRYPTO_GENESIS_FINGERPRINT` from time to time, which need to updated in Makefile manually by PR. Dynamically setting is to save this mess.
I think it is ok for devnet if we trust genesis.json is genuine one we clone from github.
