### ISSUE TITLE
Problem: no tx-query setup in client-*

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#2109]
in remote environment,
when i try to make tx using enclave
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "I/O error: Unable to write to TQE connection stream (encrypt request)"
    },
    "id": "staking_withdrawAllUnbondedStake"
}

because it received local tx-query address (which is sometimes, not accessible from outside)
so give --tx-query ?.?.?.?:port  to override,
so remote user can use sync, and make tx without problem

**Comment by tomtau** [comment]
I guess fixed with https://github.com/crypto-com/chain/pull/2108
as https://github.com/crypto-com/chain/issues/2118#issuecomment-673847828 ?
