### ISSUE TITLE
Problem: tx-query next bind

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#2118]
user will enter external-ip to here

```
 let listener = TcpListener::bind(&this.address).await?;
```                 
bind will not work
1. separate this.address to ip:port
2. replace ip with "127.0.0.1" or "0.0.0.0" local ip

**Comment by tomtau** [comment]
@leejw51crypto I added this https://github.com/crypto-com/chain/pull/2108/files#diff-b21149486d7ba1e91c22d768690196fdR34 so one can input different values for listener/binding and for what's advertised (external ip) in RPC
would that fix it?

**Comment by leejw51crypto** [comment]
test environment: this is not cloud, on premises
computer a : chain
<----> WAN 
comptuer b: client-rpc

**Comment by leejw51crypto** [comment]
> 
> 
> @leejw51crypto I added this https://github.com/crypto-com/chain/pull/2108/files#diff-b21149486d7ba1e91c22d768690196fdR34 so one can input different values for listener/binding and for what's advertised (external ip) in RPC
> would that fix it?

for me, it's just simple port issue,  after this pr is merged, i'll rebase it.

**Comment by tomtau** [comment]
@leejw51crypto I think that should be solved with that PR -- you'd set "tx_query_listen" to "0.0.0.0:3433", and "tx_query" to "222.111.333.111:3433".
there's a similar issue in a cloud environment where the local instance has an internal IP (one would listen on), but one attaches an external IP to it

**Comment by leejw51crypto** [comment]
ok, i'll start from that pr

**Comment by leejw51crypto** [comment]
solved by #1993
