### ISSUE TITLE
Problem: incorrect confirmed_transcript_hash calculation in mls

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#2145]
https://github.com/crypto-com/chain/blob/master/chain-tx-enclave-next/mls/src/group.rs#L395

`get_init_confirmed_transcript_hash` is only valid for the initial group state (0), as it hardcodes "" as `interim_transcript_hash`... for the rest, it should be calculated as:
```
interim_transcript_hash_[n+1] =
    Hash(confirmed_transcript_hash_[n] ||
        MLSPlaintextCommitAuthData_[n]);
```

**Comment by yihuang** [comment]
working on.
