### ISSUE TITLE
Problem: legacy redeem address textual conversion code

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#2150]
https://github.com/crypto-com/chain/blob/master/chain-core/src/init/address.rs#L391
`to_cro` and `from_cro` on `RedeemAddress` generally don't make sense with the existing conventions / aren't used anywhere besides the test above

**Comment by leejw51crypto** [comment]
i'll remove to_cro, from_cro

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
submitted
