### ISSUE TITLE
Problem: Ambiguous "synchronization complete" message 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#2168]
**Describe the bug**
When trying it out with @brianatcrypto, syncing works fine until it reaches the block that contains transaction(s) related to the wallet.  
When we try to sync it again with different the `batch-size`,the client-cli was "fooled" and show `Synchronization complete!`
 
**Example:**
 ```client-cli sync  --name Default_HD  -b 1000
Enter authentication token:
Synchronizing: 813 / 813 [==============================================] 100.00 % 133.16/s
Synchronization complete!

Error: Connection error: Unable to connect to TQE address: 20.49.200.60:3322
```

**To Reproduce**
1. Sync the wallet;
2. The sync is running until it reaches the "problematic"  block. "`Unable to connect to TQE address ...`" error message is shown;
3. Sync it again with different `batch-size`;
4. It shows `Synchronization complete!` but infact, it is not synced.

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
it maybe simple tx-query connection error,
could you try again?
 if external_ip:3322 port is un-reachable, then sync will not work

**Comment by lezzokafka** [comment]
> it maybe simple tx-query connection error,
> could you try again?
> if external_ip:3322 port is un-reachable, then sync will not work
> 
> so when txquery is not reachable, change batchsize make sync successful.
> i'll check that

It seems that the TQE is not working in the first place, but it is able to sync since there was no transaction in those previous blocks.

**Comment by brianatcrypto** [comment]
How can I check if TQE is not working? As I can see from log TQE is working.

**Comment by brianatcrypto** [comment]
`
 tx-query-enclave.service - Crypto.com Chain Query Enclave
   Loaded: loaded (/lib/systemd/system/tx-query-enclave.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-08-19 11:33:18 UTC; 13min ago
 Main PID: 32105 (tx-query-app)
    Tasks: 1 (limit: 4680)
   CGroup: /system.slice/tx-query-enclave.service
           └─32105 /chain/bin/tx-query/tx-query-app 0.0.0.0:3322 ipc:///chain/sockets/enclave.socket
`

**Comment by leejw51crypto** [comment]
you can try 
telnet external_ip 3433
if it's connected,  port is opened , and ready to work

**Comment by brianatcrypto** [comment]
noted, i will try, I did not open the port externally when i setup through the 1-click deployment.

**Comment by leejw51crypto** [comment]
ok, i re-produced the error,
thanks for discovery
i'll modify it asap

**Comment by lezzokafka** [comment]
Thanks again @leejw51crypto  :D
