### ISSUE TITLE
(CRO-261) Problem: no "init" for existing networks

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#726]
This issue is what @leejw51crypto had originally in mind when preparing the “developer utility” – as @tomtau  mentioned on Slack:

one needs genesis.json

some node network information (address / node_key + IP/HOSTNAME:PORT) to connect to

I think for the first one, it’s easy – just bundle this file in a tarball with binaries and have a bash script that would copy it over…

for the second one, I guess there may be some extra steps to be automated – depends on the pending enclave.

**Comment by tomtau** [comment]
the makefile can connect to testnet and automatically get binaries and has an embedded genesis.json -- closing this
