### ISSUE TITLE
(CRO-550) Problem: ambiguous error message

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#749]
when account does not exist
Error: Deserialization error: Unable to deserialize `abci_query` from JSON-RPC response for params: [String("account"), String("41c0294b79975f70c8618be33f39388941f76521"), Null, Null]

change to
account does not exist

**Comment by tomtau** [comment]
@leejw51crypto is this still the case?

**Comment by yihuang** [comment]
We have changed the error message, but judge from @lezzokafka 's reaction, there might still be confusion?

![image](https://user-images.githubusercontent.com/236070/75222797-f3555200-57df-11ea-91d1-167086622564.png)

**Comment by leejw51crypto** [comment]
i think it's solved now.
