### ISSUE TITLE
(CRO-515) Problem: chain-abci stores validator metadata

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#752]
chain-abci currently stores a lot of metadata related to validators which is unnecessary because tendermint internally maintains validator set on its own and passes metadata in ABCI Requests whenever needed. The only validator information which we may need to store is:

staking_account_address

liveness and slashing_schedule

**Comment by tomtau** [comment]
probably not relevant after https://github.com/crypto-com/chain/pull/1292
