### ISSUE TITLE
(CRO-673) Problem: storage coupled with state machine logic

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#753]
step 1 of ADR-001 (not pending any decision):

**Comment by tomtau** [comment]
> it's mainly things that can be extracted out from the storage module of chain-abci (into more high level things like -- getTx, checkOutputSpent, updates...). The purposes are two: 1) decouple plain storage operations from state machine logic, 2) check the storage-invariants needed for state machine logic (state updates persisted on-disk on commit etc.)
