### ISSUE TITLE
(CRO-473) Problem: Tx-proof not found for multi-sig demo on slow machine

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#770]
Debug Notes from @lezzokafka :

Forget to set it to zero-fee;

Tendermint/RPC web-socket changes 

 SLOW network/machine

Suggested solution: 

Downgrading  Calvin Lau Carson Yan  Mac

 In case of .tx proof not found, re-try.

 Sample wallet confirms the TX is on-chain with tendermint beforehand.

**Comment by tomtau** [comment]
can't reproduce, feel free to reopen
