### ISSUE TITLE
(CRO-644) Problem: no one-line installation for chain

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#771]
for example)curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

present one line installation
1. download tendermint
2. download pre-compiled abci, rpc, cli
3. make standard install location as default  (.cro or .cro_chain)

**Comment by yihuang** [comment]
Maybe better to have an image contains all the binaries, and an entry script to launch it as a full node.

**Comment by tomtau** [comment]
Yes, this issue should be more or less fixed by https://github.com/crypto-com/chain/pull/780

**Comment by yihuang** [comment]
> Yes, this issue should be more or less fixed by #780

Ideally, they can be solved with a common solution, but currently, #780 more about building and run from source code, rather than just get the binaries and run.

**Comment by linfeng-crypto** [comment]
if you give a tag, such as `v0.2.0`, or if the current chat just located on a git tag, it will get the released binaries from github directly.

**Comment by tomtau** [comment]
this seems to be resolved with the makefile, more or less
