### ISSUE TITLE
(CRO-464) Problem: no dynamic creation of docker-compose.yml

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#773]
except for bash scripts,  make other scripts dynamic using python3
produce docker-compose.yml on the fly, perform testing

use environment variables to communicate between steps

**Comment by tomtau** [comment]
@yihuang @leejw51crypto is this related to chain-bot?

**Comment by yihuang** [comment]
Yeah, since I just made one docker image with all binaries, I guess I need to work on this now for CRO-663. Need to replace the integration test environment set up for that PR.

**Comment by tomtau** [comment]
I think this is no longer relevant?
