### ISSUE TITLE
(CRO-677) Problem: The result of the list address API is not ordered by creation order

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#777]
The address list returned by the client should be ordered stable, e.g. by creation order.

Python integration tests use address list API to get the bonded/unbonded stacking address, it’s not stable with current API.

**Comment by yihuang** [comment]
The title should be: The result of the list address API is not ordered by creation order.

When a new address added, the whole list gets re-ordered.
It's not intuitive and affects integration test scripts that want to use the API to get specific address.
