### ISSUE TITLE
Problem: client keeps re-deriving hardened key

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#786]
Instead, it should use hmac-ed keys, as it was originally intended: https://github.com/crypto-com/chain/pull/723#pullrequestreview-335113255

A temporary patch for the slow client execution may be submitted if this fix blocks other work.

**Comment by yihuang** [comment]
Impl plan (single enckey):
- Replace `passphrase` with `enckey` in many places.
- Use `seckey` as encryption key directly, no further blake2s hash
- Use `SecBox<[u8; KeyLength]>` as the type of `seckey`.
- Derive the enckey and return it when creating wallet, maybe needs another api to retrieve enckey.
- Change integration tests accordingly.

**Comment by yihuang** [comment]
Next step:
- use blake2s hash of wallet name as salt of argon2
- use different encryption key for spending key.
