### ISSUE TITLE
Problem: integration-tests/start-local.sh is not working with mock features

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#787]
Start-local.sh comes with cargo run, no features flag for mock version

**Comment by tomtau** [comment]
this was an issue opened on Jira by @lezzokafka (just a reminder -- for the public repo work, we'll be now using ZenHub / Github issues).

@calvinaco @yihuang afaik integration-tests/start-local.sh could be superseded by chain-bot https://github.com/crypto-com/chain/tree/master/integration-tests/bot -- so I guess this script could be removed or it could be ported to over to use chain-bot.py with some default config, just a documentation needs to be updated

**Comment by yihuang** [comment]
`start-local.sh` is removed in https://github.com/crypto-com/chain/pull/890 in favor of chainbot based setup, the mock mode will be solved in #906.

**Comment by tomtau** [comment]
ok, closing this then, as it's superseded by #906
