### ISSUE TITLE
Problem: non-stable libraries in consensus-critical sections

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#801]
Bugs in these libraries could have a critical impact and library upgrades may lead to network splits, so they should be treated more carefully.

**Comment by tomtau** [comment]
needs https://github.com/crypto-com/chain/issues/804 -- can be migrated later when it's a part of tendermint-rs repo

**Comment by devashishdxt** [comment]
I'll open a PR with `tendermint-rs` to merge `abci-rs`
