### ISSUE TITLE
Problem: non-stable staked state merkle trie storage

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#802]
Currently, states are persisted and their integrity is checked using `starling` which is maintained by a single person and seems more of a hobby project.

Solution options:

1. vendor-in code, verify and maintain it ourselves

2. migrate to some more robust solutions (iAVL+, jellyfish merkle tree: https://github.com/libra/libra/blob/master/storage/jellyfish-merkle/src/lib.rs#L6 ...) -- write ADR for that first

**Comment by yihuang** [comment]
The `jellyfish-merkle` seems nicely designed, also storage agnostic, there should be no headaches to switch to that.

**Comment by tomtau** [comment]
There's also https://github.com/nomic-io/merk but it's +- similar situation as with `starling`.

`jellyfish-merkle` is nice -- we'd need to adapt the code though, as otherwise it'd bring loads of (potentially incompatible) libra-only dependencies

**Comment by tomtau** [comment]
After the examination of code by @devashishdxt, the best tradeoff may be the option 1 to vendor in the code -- currently forked to here: https://github.com/crypto-com/merkle_bit

**Comment by tomtau** [comment]
(we may maintain it in that repository, or if it diverges too much, incorporate it directly in chain repo)
