### ISSUE TITLE
Problem: chain-core is not embedded platform-friendly

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#806]
- switch to blake3 or blake2b configured with 32byte output ??
- create a heapless / arrayvec,   dependency-free (even no_std mode of SCALE codec needs alloc :disappointed: ) subset of chain-core (the relevant TX types, modified to have arrays instead of secp256k1 types etc.) -- any ideas how to do that without more complex feature-guarding ?

**Comment by tomtau** [comment]
One other thing may be to put amounts in transaction inputs or staked states, a la: https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.abnf#L143 so that embedded environment only needs to look at 1 TX at a time without complex processing of transaction inputs

**Comment by yihuang** [comment]
> One other thing may be to put amounts in transaction inputs or staked states, a la: https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.abnf#L143 so that embedded environment only needs to look at 1 TX at a time without complex processing of transaction inputs

Does the embedded environment want to do wallet syncing, or only tx signing?

**Comment by tomtau** [comment]
> Does the embedded environment want to do wallet syncing, or only tx signing?

only tx signing, but the embedded environment needs to display amounts (+ fee) for verification in the context of one tx -- here's one high level article that talks about some of the challenges: https://blog.trezor.io/what-segregated-witness-means-for-trezor-808c790a05bd

**Comment by yihuang** [comment]
> > Does the embedded environment want to do wallet syncing, or only tx signing?
> 
> only tx signing, but the embedded environment needs to display amounts (+ fee) for verification in the context of one tx -- here's one high level article that talks about some of the challenges: https://blog.trezor.io/what-segregated-witness-means-for-trezor-808c790a05bd

So the UTxO set is not synced from the network, but provided by the user?

**Comment by tomtau** [comment]
Yes, that's always the case with embedded environments, as they can't store the full node data.

**Comment by yihuang** [comment]
> Yes, that's always the case with embedded environments, as they can't store the full node data.

So the HW wallet can trust the user who provided the UTxO, can we only add the amount in the data provided to the HW wallet, no need to add the amount to `Tx` type on-chain?

**Comment by tomtau** [comment]
> So the HW wallet can trust the user who provided the UTxO, can we only add the amount in the data provided to the HW wallet, no need to add the amount to Tx type on-chain?

No, the HW wallet should always verify these things and display them for the user to double check before it signs (what is being sent to the HW wallet may not be what the user thinks it was sent, e.g. due to malware running on the host) -- the only difference is:
if amounts aren't mentioned in inputs, the host program will need to stream all the UTXOs to the wallet, the wallet will need to parse them, grab the amount and compute the TX-ids of all of them... and then assemble the desired TX from it.
So the logic is more complex, given the restricted bandwidth (e.g. ~200 bytes in one host->wallet exchange) and device memory.

**Comment by tomtau** [comment]
things done:
- switched to blake3
- fees are not flexible anymore -- a device app just need to know the fee policy + the TX size... i.e. it won't accidentally create a TX that pays a huge fee

things delayed for other time:
- heapless dependency-free chain-core -- initial HW app may use C and reimplement SCALE in it; this may be investigated later when Rust support https://github.com/LedgerHQ/rust-app-demo becomes more mature
