### ISSUE TITLE
Problem: enclave code directly contacts IAS

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#817]
As there may be other enclave code, like https://github.com/crypto-com/chain-docs/blob/master/plan.md#transaction-data-bootstrapping-enclave-tdbe , it'll be desirable to have the IAS configuration in one place, so enclave code wouldn't directly call IAS, but use a proxy (that has IAS api key etc.)

**Comment by devashishdxt** [comment]
@tomtau A few questions about IAS proxy:

- Should this be a thin proxy or a fat one?
  - Thin proxy: Receives HTTP(S) request, adds IAS api key in header, forwards that request to IAS and returns the response directly to caller.
  - Fat proxy: Runs a TCP server (TLS?), get binary encoded data as request, convert request data in format expected by IAS, parse the response and send binary encoded data back to client over TCP.
- Should this be over HTTPs (if thin)/TLS (if fat)?

**Comment by tomtau** [comment]
> Should this be a thin proxy or a fat one?
it'll make sense to combine with "AESM proxy" (or whatever to call it) functionality for obtaining quotes. Whatever is simpler and makes sense.

> Should this be over HTTPs (if thin)/TLS (if fat)?
whatever is the simplest -- enclave will need to fully verify the responses anyway
