### ISSUE TITLE
Problem: outdated README

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#818]
e.g. one may need clang/g++

**Comment by yihuang** [comment]
Also update the enclave building README.

**Comment by tomtau** [comment]
> Remove the chain-tx-enclave/README.md

or just keep there still relevant info (or update it) or move to somewhere else? Probably only still relevant info about updating Rust SGX SDK

**Comment by yihuang** [comment]
Another issue is, we actually have four ways to build now:
- build docker image: `docker build -f docker/Dockerfile.new .`
- native build: prepare env and run `./docker/build.sh`
- `make build`, which is basically: `docker run -v `pwd`:/chain cryptocom/chain:latest` run_build`
- `drone exec --include build`
