### ISSUE TITLE
Problem: no import/export for non-HD keys

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#827]
reported by @leejw51crypto 
"for resync, user remove .storage then also wallet information also gone so separate storage for wallet, sync

for reference).storage/wallet <- for wallet.storage/sync <- for sync.cro_storage <- for chain"

**Comment by yihuang** [comment]
`WalletState` and `SyncState` should be stored together, other stuff should be stored together.

**Comment by yihuang** [comment]
We also need a backup for HD wallet, other than the mnemonic words, there are staking address count, transfer address count needs to backup, so when we restore, we have the same wallet.
