### ISSUE TITLE
Problem: client uses a custom tendermint-rs fork

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#828]
migrate to upstream when possible

**Comment by yihuang** [comment]
Status report on this.
there are currently two issues pending:
- One is stability of lite client api, a new API design just merged several days ago(https://github.com/interchainio/tendermint-rs/pull/114).
- Another one is empty value serialization issue(https://github.com/interchainio/tendermint-rs/pull/103#issuecomment-570100348), which is not merged yet. And to solve this problem nicely, it probably need some changes in `amino-rs`.

**Comment by Liamsi** [comment]
interchainio/tendermint-rs#114 is merged btw. I'm looking through https://github.com/interchainio/tendermint-rs/pull/103 and I'm inclined to merge this too. We will still explore other options but I'd think it would be valuable to unblock you to switch to upstream and have sth. that works even not optimally for now.

**Comment by tomtau** [comment]
can move to the new "light-client" crate

**Comment by yihuang** [comment]
fixed by https://github.com/crypto-com/chain/pull/1901
