### ISSUE TITLE
Problem: no automated test for jailing using byzantine faults

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#850]
two validators at the same time – double sign byzantine fault, one of the validators was “duplicate” (had the same validator key)
3 nodes

@leejw51crypto Jason can help with this issue

**Comment by yihuang** [comment]
The test procedure:
- 3 nodes
- node2 has more than 2/3 voting powers
- node0 and node1 have same validator seed, both have 0 bonded coins initially, only unbonded coins.
- start the nodes, and stop node1 immediately.
- withdraw, deposit and join node0.
- start node1, check node0 punished.
