### ISSUE TITLE
Problem: multi-node integration tests not executed on CI

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#853]
Most of the multi-node integration tests *don't* need spinning up any enclaves (can use the mock compilation or use the SW emulation mode), as all transactions are public (unjail, nodejoin...) and entirely processed by chain-abci.

The current pipeline was disabled mainly because it wasn't stable and didn't do any cleaning: https://github.com/crypto-com/chain/blob/master/.drone.yml#L126

Instead of having a separate pipeline, the multi-node integration tests would ideally be added to the existing integration test pipeline -- either on Travis CI or on Drone.

@leejw51crypto Jason can help with this

**Comment by leejw51crypto** [comment]
let's build once for all integration test.
and remove all compiling tmp files after test
