### ISSUE TITLE
Problem: inconsistent wallet storage service API design

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#854]
### Context

Current wallet service API provides fine-grained API to access stored objects, which allows great extensibility of underlying storage choice, for example:

- You can store different fields of one object in different DB.
- You can store different types of objects in different DB.

But it also causes some inefficiencies in business code, for example, each time you want to access some field of an object, it needs to load the whole object in memory, return the field, drop the object, and encryption/decryption also happens in this process for secure storage.

So when implementing [CRO-578](https://github.com/crypto-com/chain/pull/677), I have to break this abstraction, and create a new one, which is basically:

- load the object as a whole
- save the object as a whole
- work on the object in memory through methods and pub fields

The new `load/save` methods are simply functions that take storage as the first argument, and business code only needs to hold a storage instance to `load/save` different types of objects.

Currently, these two design co-exists, I think we need to unify them.

### Proposal

[Experement code for proposed design](https://github.com/yihuang/chain/commit/6280447be4227cfd4b94f15ae44c3cb9f4a91448#diff-1dd41e2574b6fd603c92def62f2457b8)

The idea is, since we need the `load/save` style API to improve efficiency, we can simply deprecate the fine-grained service API, and move some service methods into the object itself. Also, we can move `load/save` API into an extension trait of `Storage`, make it a bit nicer to use.

Some business code changes:

```rust
// Before
self.wallet_service.view_key(name, enckey)
// After
self.storage.get_value_secure::<Wallet>(name, enckey)?.view_key
```

```rust
// Before
self.wallet_service.add_public_key(name, enckey, &public_key)?;
// After
self.storage.modify_value_secure(name, enckey, |wallet: &mut Wallet| {
    wallet.add_public_key(public_key)
})?;
```

For wallet synchronizer or other long-running processes, you can load the object as a whole and cache it:

```
let sync_state: SyncState = self.storage.load_value(name)?;
```

To implement a new storage value type:

```rust
impl StorageValueType for SyncState {
    fn keyspace() -> &'static str {
        "core_wallet_sync"
    }

    // only used for error messages
    fn name() -> &'static str {
        "SyncState"
    }
}
```

#### Advantages

- We can remove many lines of code of the service struct in favor of the common `load/save/modify` API.
- Easy to support newstorage data types. 
- Business code can work on the whole object in memory.

#### Disadvantages

- The business code actually a bit longer than before, because we eliminated the service APIs altogether.
- Not able to store different fields of one object into different storages, but we can split the object into smaller objects though.

#### Neutral

- Business code holds a single storage instance, has access to all the storage-related APIs through extension traits.

### How to support different storages

It's able to support multiple storages with the new API, we can implement something like `StorageRouter`, which implement `Storage` trait, and route the calls to different underlying `Storage` instances based on `keyspace` argument.

**Comment by devashishdxt** [comment]
> But it also causes some inefficiencies in business code, for example, each time you want to access some field of an object, it needs to load the whole object in memory, return the field, drop the object, and encryption/decryption also happens in this process for secure storage.

Is this the only issue you are facing? Because it is very easy to mitigate this issue without a full redesign. If there are other issues, can you please mention those here?

**Comment by yihuang** [comment]
> > But it also causes some inefficiencies in business code, for example, each time you want to access some field of an object, it needs to load the whole object in memory, return the field, drop the object, and encryption/decryption also happens in this process for secure storage.
> 
> Is this the only issue you are facing? Because it is very easy to mitigate this issue without a full redesign. If there are other issues, can you please mention those here?

Ok, here is my thinking process:
- We need an API(say `load_wallet`) to load the object as a whole and expose the internal of the object to work on it in memory.
- If we add this `load_wallet` into `WalletService` and expose the internals of `Wallet`, then we have two ways to do the same thing, for example:
```
wallet_service.public_key(name, enckey)
wallet_service.load(name, enckey).public_key
```
- So it's good to remove the `public_key` API from `WalletService` to keep it simple.
- Follow this process, `WalletService` would only left with something like `load/save/modify`.
- Follow this process, `SyncStateService` and `WalletStateService` can be simplified as the same.
- Follow this process further, why not merge them into one unified `load/save/modify` API.

Another point is to make the API as a service wrapper struct of storage, or simply extension trait of storage, the latter would be a bit simpler to use.

**Comment by devashishdxt** [comment]
> * So it's good to remove the `public_key` API from `WalletService` to keep it simple.

Why? Places where we only need `public_key`, `wallet_service.public_key(name, enckey)` is more simpler and readable. 

> Some business code changes:
> 
> ```rust
> // Before
> self.wallet_service.view_key(name, enckey)
> // After
> self.storage.get_value_secure::<Wallet>(name, enckey)?.view_key
> ```
> 
> ```rust
> // Before
> self.wallet_service.add_public_key(name, enckey, &public_key)?;
> // After
> self.storage.modify_value_secure(name, enckey, |wallet: &mut Wallet| {
>     wallet.add_public_key(public_key)
> })?;
> ```

For examples you mentioned in description, the _before_ version seems so much more simpler, readable and easily comprehensible. For places where we need whole object in memory, we can expose `load`, `save` and `modify` functions for each service.

**Comment by yihuang** [comment]
I'm closing this, based on some slack discussion, the current status is not that bad, we can wait for the future feature request to decide the correct design.
