### ISSUE TITLE
Problem: no blacklisting of byzantine validators

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#856]
@lezzokafka pointed out in the past, it may be desirable to blacklist validator keys once they had a byzantine fault

**Comment by devashishdxt** [comment]
How about not allowing `Unjail` for validators with byzantine faults?

**Comment by lezzokafka** [comment]
@devashishdxt 
It was done by [tombstone](https://docs.cosmos.network/master/modules/slashing/07_tombstone.html) in Cosmos.

**Comment by tomtau** [comment]
> How about not allowing `Unjail` for validators with byzantine faults? This will have same effect.

no, that has a greater effect of not being able to use 100% of the remaining funds... For example:
- a validator key was compromised
- the affected validator would later want to unjail and join again with its new better-secured infra and a corresponding new validator key

**Comment by tomtau** [comment]
not relevant after https://github.com/crypto-com/chain/pull/1292 https://github.com/crypto-com/chain-docs/pull/108#issuecomment-599843715
