### ISSUE TITLE
Problem: complex Bash setup for integration test environment

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#858]
to prevent accidental errors, it may be easier if the integration test setup is done in a higher-level language, e.g. utilise the chain-bot setup scripts

**Comment by yihuang** [comment]
# Plan

## Build

### Local mode

A script to build all binaries locally by calling `cargo` and `make`, all the result binaries reside in single place ready to run. Able to work with different build profiles(debug/release).

- Enclave makefile needs to be changed to work with different build profiles, basically some directores need to be changed.
- enclaves need to renames to be able to reside in same directory.

### Docker mode

- Simply run the above script in a proper builder base image.
- Copy the binaries from builder image to a minimal runtime image, with only nesserery dependencies included(sgx).
- Include some minimal process manager, supervisor is ok except the python dependency, other options would be ok if have enough feature set and smaller dependencies.
- A entry script to start the process manager, which starts all the processes for a full node.
- A single mount point to mount config files for all the processes, or builtin chainbot to initialize configurations when startup.
- This image can be published to docker hub for each release.

## Prepare Test environment

Simply run `chainbot`.

For existing integration tests, needs to setup both zerofee and withfee environments.

Other multi-node tests is out of scope of this issue.

## Run test

### Local mode

Spawn the processes with `supervisord`, them `npm run test`.

### Drone mode

Run above script in docker pipeline with some proper base image with following dependencies:

- Basic build dependencies: cargo, cmake, zmq, clang, etc.
- python3/pip3.
- sgx sdk and runtime.
- expose sgx device

**Comment by tomtau** [comment]
> enclaves need to be renamed to be able to reside in the same directory.
the enclave files (`.signed.so`)?

**Comment by yihuang** [comment]
> > enclaves need to be renamed to be able to reside in the same directory.
> 
> the enclave binary files (`.signed.so`)?

Yeah. I think it would be good to do this, are there any side effects?

**Comment by tomtau** [comment]
opened this issue https://github.com/crypto-com/chain/issues/868

**Comment by yihuang** [comment]
For the enclave build part, how about I change it to the build system I experimented before (https://github.com/yihuang/chain/blob/enclave-building/chain-tx-enclave/common.mk, https://github.com/yihuang/chain/blob/enclave-building/chain-tx-enclave/tx-validation/enclave/build.rs). It's already tested on sgx hw mode.

**Comment by tomtau** [comment]
opened #869 for that
