### ISSUE TITLE
Problem: duplicated enclave code

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#861]
common code can be shared in `enclave-t-common`

**Comment by yihuang** [comment]
- `Seal/Unseal`, it's several lines of unsafe code repeated at several places, it's good to encapsulate them like https://github.com/yihuang/chain/blob/enclave-building/sgx-wrapper/src/sgx.rs#L8.
- Makefile of both enclaves are almost the same, they can be easily shared.
- attested tls setup code seems to be reusable, but I'm not expert on that, and it's only used once by `tx-query`, so maybe there's no need to move that.

**Comment by tomtau** [comment]
for the last part, we'll see after this: https://github.com/crypto-com/chain/issues/860

**Comment by tomtau** [comment]
makefiles here: https://github.com/crypto-com/chain/issues/869

**Comment by tomtau** [comment]
stuff is now shared in enclave-ra and enclave-utils https://github.com/crypto-com/chain/tree/master/chain-tx-enclave-next
