### ISSUE TITLE
Problem:no one-line installation of chain

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#862]
for example)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

provide one-line installation for local drone 
1. download tendermint automatically
2. download pre-compiled enclave binaries
3. run setup automatically
4. run the chain after setup

**Comment by tomtau** [comment]
duplicate: https://github.com/crypto-com/chain/issues/771
