### ISSUE TITLE
Problem: repeating complex set of arguments to chain-abci

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#864]
As there's a quite of a few arguments one needs to provide to chain-abci, it may be a bit error-prone when restarting it (as experienced with the tx-query argument).
It'd be desirable to have an option to start chain-abci without providing any arguments or only one argument, so that the rest is read from a file.

Perhaps chain-abci could read from a JSON or TOML file put in `DATA_DIRECTORY/config/...` (where DATA_DIRECTORY is .cro-storage or what's passed in as `-d` argument) which contains a subset of AbciOpt?

**Comment by linfeng-crypto** [comment]
should I keep the original argument to refresh the configure?

**Comment by tomtau** [comment]
if the argument is provided and there's a configuration file, the argument should have a precedence
