### ISSUE TITLE
Problem: no way to run client in air-gapped settings

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#865]
https://en.wikipedia.org/wiki/Air_gap_(networking)

e.g. in this setting:

A. Online machine (doesn't have keys)

B. Offline isolated machine (has keys)

we may wish to have the following workflow (using client-cli or equivalents):

1. On A., dump inputs (staked state given an address, network params etc.) to a file F-A

(transfer F-A to B, e.g. on a USB flash drive)

2. On B. read F-A, display it, create a signed transaction using it -- dump the plain signed transaction payload to a file F-B

(transfer F-B to A)

3. On A., (obfuscate if relevant), display and broadcast the transaction created from F-B

**Comment by yihuang** [comment]
There's also a practice to use qr-code and scanning tool instead of USB flash driver to transfer the information ;D
