### ISSUE TITLE
Problem: compiled enclave file names collide

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#868]
it may be desirable to have the launcher configurable -- e.g. using an environment variable (if not set, just use the current fixed value)

**Comment by yihuang** [comment]
Can we use fixed unique value directly in the code, something like `tx-validation.signed.so`, `tx-query.signed.so`, then it's no need to use an environment variable to customize?
Change `init_enclave` to like `init_enclave(name: &str, debug: bool)`.

**Comment by tomtau** [comment]
that's also fine and perhaps simpler -- I opened this issue, because I wasn't sure if the renaming would break things -- I changed the title to reflect that
