### ISSUE TITLE
Problem: enclave code not covered by cargo tools

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#870]
`cargo fmt`, `cargo clippy`, test coverage, etc. Because they can't be built by cargo directly.

**Comment by tomtau** [comment]
@yihuang this will be the case with the current SDK.
For the moment, the approach could be:
1) for SDK-independent logic, isolate that into SGX-friendly crates (like `enclave-protocol`, `chain-tx-validation`, `chain-core`)  -- that then gets covered automatically
2) for SDK-dependent logic, one can't use the standard cargo tooling like `cargo test` -- instead, it'll need the custom `sgx-test` / `cov` feature-guard, see https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/samplecode/sgx-cov

**Comment by yihuang** [comment]
> @yihuang this will be the case with the current SDK.
> For the moment, the approach is:
> 
> 1. for SDK-independent logic, isolate that into SGX-friendly crates (like `enclave-protocol`, `chain-tx-validation`, `chain-core`)  -- that then gets covered automatically
> 2. for SDK-dependent logic, one can't use the standard cargo tooling like `cargo test` -- instead, it'll need the custom `sgx-test` / `cov` feature-guard, see https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/samplecode/sgx-cov

Yeah, `cargo test` is still problematic, but with current approach, `cargo fmt` and `cargo clippy` is runnable on all the codes.

**Comment by tomtau** [comment]
yes, `fmt` and `clippy` could have extra steps in CI pipelines to check the SDK-dependent enclave code
