### ISSUE TITLE
Problem: not clear from name what unit a parameter is in

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#874]
Some parameters are in seconds, some are in blocks...
it may be clearer if the name said it, e.g. by post fixing with `_sec`

**Comment by lezzokafka** [comment]
Here are  some examples: 

- In seconds:  
```
    "unbonding_period"
    "jail_duration"
    "slash_wait_period"
    "distribution_period" 
```

- In blocks:
```
       "block_signing_window"
       "missed_block_threshold"
       "evidence"
```

**Comment by yihuang** [comment]
Also:
```
monetary_expansion_r0: millis,
monetary_expansion_decay: macros,
```

**Comment by tomtau** [comment]
Some of the parameters disappeared (e.g.     "unbonding_period", "jail_duration", "slash_wait_period" are all replaced by evidence age), some were renamed ("reward_period_seconds")
and some seem OK ("block_signing_window" / "missed_block_threshold" kind of hints it's in blocks?).

the reward formula parameters... I don't know if they can be given some meaningful unit name given their ranges: https://github.com/crypto-com/chain-docs/blob/master/docs/protocol/reward-and-punishments.md#rewards-network-parameters-for-monetary-expansion

anyway, feel free to reopen issues for any parameters that could be good to rename
