### ISSUE TITLE
Problem: light client verification fails when a validator with more than >1/3 voting power is jailed or unbonds

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#911]
it may be a feature or a bug

**Comment by yihuang** [comment]
If there are less or equal then 2/3 voting power, isn't tendermint stop to produce blocks?

**Comment by tomtau** [comment]
> If there are less or equal then 2/3 voting power, isn't tendermint stop to produce blocks?

Yes... I think the steps to reproduce this scenario if I remember correctly from @devashishdxt description:

1. start a network where one validator has more than 1/3 voting power
2. unbond some amount (block aren't produced)
3. rejoin the validator set by deposittx to that validator's associated staked state (blocks are produced)

not sure if this can be reproduced after https://github.com/crypto-com/chain/issues/910 was fixed

**Comment by tomtau** [comment]
probably can't be reproduced now
