### ISSUE TITLE
Problem: Unable to restore wallet with the same seed (or mnemonic words) as existing wallet.

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#914]
Steps to reproduce:
```
$ chainrpc.py wallet restore "pony thank pluck sweet bless tuna couple eight stove fluid essay debate cinnamon elite only" --name Default
$ chainrpc.py wallet restore "pony thank pluck sweet bless tuna couple eight stove fluid essay debate cinnamon elite only" --name test
Traceback (most recent call last):
    ...
jsonrpcclient.exceptions.ReceivedErrorResponseError: Decryption error: Incorrect enckey: Unable to unlock stored values
```

The reason is different wallets have different encryption keys now, so it can't load the key pair created by the other wallet.

**Comment by tomtau** [comment]
@yihuang you get this error `jsonrpcclient.exceptions.ReceivedErrorResponseError: Decryption error: Incorrect enckey: Unable to unlock stored values`'

after executing the second `restore`? or after some other command (not sure if to interpret "..." as other commands or a trimming of the error message)

**Comment by yihuang** [comment]
> @yihuang you get this error `jsonrpcclient.exceptions.ReceivedErrorResponseError: Decryption error: Incorrect enckey: Unable to unlock stored values`'
> 
> after executing the second `restore`? or after some other command (not sure if to interpret "..." as other commands or a trimming of the error message)

It's trim of error messages, I edited a bit to make it clearer.

**Comment by yihuang** [comment]
A potential solution might be to prefix the key of `KeyService` (maybe other services as well if necessary) with the wallet name.

**Comment by tomtau** [comment]
I guess both are fine -- what are the impacts (positive/negative) of each?

**Comment by yihuang** [comment]
Option two:
Positives:
- Able to iterate key pairs of a wallet without referencing other information.
Negatives:
- Have to load/save all key pairs in bulk, even if we only want to operate on a single one. Since we already go with this structure in `Wallet`, so I think it's fine.
- Store view key pair with a different storage key if we want to encrypt it with a different token.

**Comment by leejw51crypto** [comment]
i think option 1 is good
KEYSPACE+ wallet_name prefix

**Comment by yihuang** [comment]
> i think option 1 is good
> KEYSPACE+ wallet_name prefix
> 
> a little in-efficient, but will be no problem

Option two would allow import/export wallet as a whole, without decrypting information.

**Comment by leejw51crypto** [comment]
as long as we use enckey per wallet, backup & restore with one shot is not possible

**Comment by yihuang** [comment]
> as long as we use enckey per wallet, backup & restore with one shot is not possible

If the storage is like `wallet name -> encrypted value`, we can backup the "encrypted value" without decrypte it.

**Comment by leejw51crypto** [comment]
just copying with encrypted state is OK.
but i think it's different command.
how about "backup & restore" 

this pr is for decrypt, encrypt the wallets.
