### ISSUE TITLE
Problem: Ongoing deposit transaction don't have pending value in balance.

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#929]
Ongoing withdraw and transfer transactions are reflected in `pending` value of balance, but deposit transaction is not.

**Comment by tomtau** [comment]
maybe related to https://github.com/crypto-com/chain/issues/846 ?

**Comment by yihuang** [comment]
> maybe related to #846 ?

I think they are independent. This issue is because deposit transaction don't create a `PendingTransaction` which marks the UTxO as spent.

**Comment by yihuang** [comment]
Clarify the semantics of pending balance:
* withdraw 10 coins,  balance: `total: 10, available: 0, pending: 10`
* after confirmed, balance: `total: 10, available: 10, pending: 0`
* deposit 10 coins, should it be `total: 10, available: 0, pending: -10`?
* after confirmed, balance: `total: 0, available: 0, pending: 0`

**Comment by devashishdxt** [comment]
The idea behind pending balance was to mark “potentially spent UTXOs”. Since withdraw transaction doesn’t spend any UTXOs, it shouldn’t change the balance. Balance will only change after syncing.

**Comment by yihuang** [comment]
> The idea behind pending balance was to mark “potentially spent UTXOs”. Since withdraw transaction doesn’t spend any UTXOs, it shouldn’t change the balance. Balance will only change after syncing.

I updated the balance state after withdraw. But my question is about the deposit part, with an ongoing deposit, should the pending be 0 or negative value?

**Comment by tomtau** [comment]
I think the value should be consistent with what's in transfertx -- e.g. if one does transfertx to a wallet outside, does it show 0 or -amount pending?

**Comment by lezzokafka** [comment]
Remarks: 

For example I have two wallets **A** and  **B** with transfer addresses **T_a**, **T_b** and staking addresses **S_a**, **S_b**. 

- All good if I make any deposit from **T_a** to  **S_a** ( address under the control of the same wallet);

- However, If  I deposit from **T_b** to **S_a** , this sort of "**outgoing**" deposit would not be shown in the history (neither being reflected in the balance).

**Comment by yihuang** [comment]
> Remarks:
> 
> For example, If I have two wallets **A** and **B** with transfer addresses **T_a**, **T_b** and staking addresses **S_a**, **S_b**.
> 
> * All good if I make any deposit from **T_a** to  **S_a** (address under the control of the same wallet);
> * However, If  I deposit from **T_b** to **S_a** , this sort of "**outgoing**" deposit would not be shown in the history (neither being reflected in the balance).

Sounds like a bug.

**Comment by lezzokafka** [comment]
> Sounds like a bug.

By the way, in the second case, the deposit did go through and changed the _Bonded_ value of **S_a**.

**Comment by yihuang** [comment]
Current behavior from reading code, pending value only concerns with incoming coins of pending tx, no relation with outgoing coins, maybe it's good enough for now:

```
total = available + pending
pending = sum(incoming coins of pending tx)
available = sum(synced utxo - spent by pending tx)
```

### pending tx with n incoming coins

```
total = original + n
pending = n
available = original
```

### pending tx spend n coins

```
total = original - n
pending = 0
available = original - n
```
