### ISSUE TITLE
Problem: Client has no stable way to wait for successful execution of transaction

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#948]
Currently, there are different ways to archive this:
- Wait for several blocks(1 is not enough) (using `latest_block_height` of `status` endpoint), not stable.
- Wait for the pending value of wallet balance to become zero, only works for some types of transactions, and assuming there are no concurrent tasks on the same wallet.
- Query `abci_query` with path `meta` and txid. There's no way to detect failure except timeout. Also not all kinds of transactions(deposit) can be queried with it.

It would be good for client-rpc/client-cli to provide the behaviour of `broadcast_tx_commit`.

**Comment by yihuang** [comment]
Are there side effects if we simply change `broadcast_tx_sync` to `broadcast_tx_commit`.

**Comment by devashishdxt** [comment]
> Are there side effects if we simply change `broadcast_tx_sync` to `broadcast_tx_commit`.

Tendermint [documentation](https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit):
> IMPORTANT: use only for testing and development. In production, use BroadcastTxSync or BroadcastTxAsync. You can subscribe for the transaction result using JSONRPC via a websocket. See https://docs.tendermint.com/master/app-dev/subscribing-to-events-via-websocket.html

**Comment by yihuang** [comment]
Ok, also maybe can use tendermint `/tx` endpoint to query the status of any transaction, I can try that.

**Comment by devashishdxt** [comment]
> Ok, also maybe I can use the tendermint `/tx` endpoint to query the status of any transaction, I can try that.

Why not use websocket message to get the transaction result (as mentioned in documentation)?

**Comment by yihuang** [comment]
> > Ok, also maybe I can use the tendermint `/tx` endpoint to query the status of any transaction, I can try that.
> 
> Why not use websocket message to get the transaction result (as mentioned in documentation)?

You mean setup a worker thread to do the subscribing? I think it's too heavyweight for integration tests.

**Comment by yihuang** [comment]
The `/tx` endpoint of tendermint seems don't work well:
```
$ curl http://127.0.0.1:27757/tx\?hash\=0x62ee4ac2d1b2dd31bace7b5fd5a863ead8bb43f364ac002ee87f2b705c2941b1
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Tx (62EE4AC2D1B2DD31BACE7B5FD5A863EAD8BB43F364AC002EE87F2B705C2941B1) not found"
  }
}
```

**Comment by yihuang** [comment]
It can use `/tx_query` rpc endpoint to query transaction status with our transaction id (
https://github.com/yihuang/chain/blob/new-multi-node/integration-tests/multinode/common.py#L22) which can solve this problem for integration tests.

**Comment by tomtau** [comment]
> The `/tx` endpoint of tendermint seems don't work well:
> 
> ```
> $ BASE_PORT=27770 chainrpc.py staking withdraw_all_unbonded 0x4873342955072f305d2a926b67d97e2fd1442f37 dcro1e2kl3xj7g3cvjlamx3jm7vxth02xet0ztvtjtqyqnczmtjulcy4q5r0pva
> 62ee4ac2d1b2dd31bace7b5fd5a863ead8bb43f364ac002ee87f2b705c2941b1
> $ curl http://127.0.0.1:27777/tx\?hash\=0x62ee4ac2d1b2dd31bace7b5fd5a863ead8bb43f364ac002ee87f2b705c2941b1
> {
>   "jsonrpc": "2.0",
>   "id": "",
>   "error": {
>     "code": -32603,
>     "message": "Internal error",
>     "data": "Tx (62EE4AC2D1B2DD31BACE7B5FD5A863EAD8BB43F364AC002EE87F2B705C2941B1) not found"
>   }
> }
> ```
> 
> Is there difference between our txid and tendermint txid?

yes, there's a difference -- our txid is a digest of the plain transaction-only payload (currently with blake2s)... tendermint txid is afaik sha256 of the whole thing (including a witness or of obfuscated data)

**Comment by tomtau** [comment]
@yihuang tendermint txid should be returned as a result of any "broadcast_tx_..." operation
