### ISSUE TITLE
Problem: Unable to connect to TQE address: sgx-query:26651 when running chain with Docker

### ISSUE THREAD

**Issue by foreseaz** [crypto-com/chain#950]
**Describe the bug**
After kicking off the chain by `make run` with docker, `withdrawal` cannot complete because of the error of `Connection error: Unable to connect to TQE address: sgx-query:26651`.

**To Reproduce**
1. `make run` after `make build`
2. Following the guide of `Send Your First Transaction`, and run `./target/debug/client-cli transaction new --name Default --type Withdraw`

**Screenshots**
![image](https://user-images.githubusercontent.com/5697641/72788917-aa086480-3c6d-11ea-940b-3f5d590803e3.png)

**Comment by yihuang** [comment]
How about log into a linux machine and follow these instructions: https://github.com/crypto-com/chain/blob/fbb7c4b29c164cadfc70b05583e9237e63e68a84/integration-tests/README.md#run-manually.

**Comment by foreseaz** [comment]
@yihuang I haven't tried your test flow, but with the guide from @linfeng-crypto  I can successfully run the Withdraw command in a new docker container (which connects to the network of running containers). Here the issue occurs when I run the commands on the Linux directly. So I think it's related to some network issues, and should be better handled in the `Makefile`.  @linfeng-crypto

**Comment by tomtau** [comment]
not sure if still relevant, as there's now tx-query-next code -- closing this now, but feel free to reopen
