### ISSUE TITLE
Problem: Reward is lower than expected

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain#954]
**Example:**
`Total_staking: 1.5 Billion` 
`"monetary_expansion_r0\":350`
`"monetary_expansion_tau\":14500000000000000 `
`"distribution_period\":86400` ( One day) 
`"monetary_expansion_decay\":999860`

At the end of the first day, 1688331667524 (16.8 K of CRO ) was "minted" and sent to the reward pool. One of the validator's (with 33% of the voting power) staking address gain from 500,000,000 to 500,005,639 
  
**Expected behaviour:**
The expected size  of the reward distribution should be ~ 1.2 M CRO for that period (about 28% p.a. for 1.5 B CRO staking)

**Comment by lezzokafka** [comment]
Suggestions:
 - Calculate the reward p.a. (**R**) using function `reward::monetary_expansion`;
- Get the reward rate for the reward period, for example, if **R**=30% and reward being distributed daily, the reward rate for that day should be `1-(1.3)^{1/365}  ~ 0.071906461 %`;
- Calculate the "minted"  value based on the total staking and the reward rate for that period.

**Comment by yihuang** [comment]
> Suggestions:
> 
> * Calculate the reward p.a. (**R**) using function `reward::monetary_expansion`;
> * Get the reward rate for the reward period, for example, if **R**=30% and reward being distributed daily, the reward rate for that day should be `1-(1.3)^{1/365}  ~ 0.071906461%`;
> * Calculate the "minted"  value base on the total staking and the reward rate for that period.

```
S = total_staking
R = S * R0 * exp(-S/tau)
year_seconds = 365 * 24 * 60 * 60
reward_rate = 1-(1 + R)^{reward_period_seconds/year_seconds}
new_minted = ?
```

**Comment by lezzokafka** [comment]
> S = total_staking
> R = S * R0 * exp(-S/tau)
 
Hummm....
 - The equation  `R0 * exp(-S/tau)` is to calculate the reward rate per annum.  ( this is what `reward::monetary_expansion` already does, need no changes to that )

- Then we take the `distribution_period ` network parameter into account to calculate what should be the corresponding  reward rate for that period: 
`1- ( 1+ R0 * exp(-S/tau) )^{reward_period_seconds/year_seconds} `

**Comment by yihuang** [comment]
> > S = total_staking
> > R = S * R0 * exp(-S/tau)
> 
> Hummm....
> 
> * The equation  `R0 * exp(-S/tau)` is to calculate the reward rate per annum.  ( this is what `reward::monetary_expansion` already does, need no changes to that )
> * Then we take the `distribution_period` network parameter into account to calculate what should be the corresponding  reward rate for that period:
>   `1- ( 1+ R0 * exp(-S/tau) )^{reward_period_seconds/year_seconds} `

```
S = total_staking
R = R0 * exp(-S/tau)
year_seconds = 365 * 24 * 60 * 60
reward_rate = 1-(1 + R)^{reward_period_seconds/year_seconds}
new_minted = S * reward_rate
```
Like this?

**Comment by lezzokafka** [comment]
> > > S = total_staking
> > > R = S * R0 * exp(-S/tau)
> > 
> > 
> > Hummm....
> > 
> > * The equation  `R0 * exp(-S/tau)` is to calculate the reward rate per annum.  ( this is what `reward::monetary_expansion` already does, need no changes to that )
> > * Then we take the `distribution_period` network parameter into account to calculate what should be the corresponding  reward rate for that period:
> >   `1- ( 1+ R0 * exp(-S/tau) )^{reward_period_seconds/year_seconds} `
> 
> ```
> S = total_staking
> R = R0 * exp(-S/tau)
> year_seconds = 365 * 24 * 60 * 60
> reward_rate = 1-(1 + R)^{reward_period_seconds/year_seconds}
> new_minted = S * reward_rate
> ```
> 
> Like this?

Looking good!

Sorry, just a quick fix: For `reward_rate`, it should be 
` reward_rate= (1 + R)^{reward_period_seconds/year_seconds}  - 1 `

 and the `year_seconds` can be hard-coded as well.

**Comment by yihuang** [comment]
Final:
```
S = total_staking
R = R0 * exp(-S/tau)
P = reward_period_seconds / (365 * 24 * 60 * 60)
reward_rate = pow(1 + R, P) - 1
new_minted = S * reward_rate
```

Transform the `pow` into `exp` and `log`.
```
pow(1 + R, P)
= exp( P * log(1 + R) )
```

Inline:
```
new_minted = S * (exp(P * log(1 + R0 * exp(-S/tau))) - 1)
```

![MainEq1](https://user-images.githubusercontent.com/236070/73426644-dc057f00-436f-11ea-8aea-928c150b4cdf.gif)

![MainEq1-1](https://user-images.githubusercontent.com/236070/73426698-fa6b7a80-436f-11ea-914c-e4c5c99fcfb5.gif)

**Comment by yihuang** [comment]
Further substituted with the better-converged version of `exp` and `log`:
```
exp2(x, y) = exp(x / y)
log2(x, y) = log(1 + x / y)
```
```
M = S * (exp2(P * log2(R0 * exp2(-S, tau), 1000), Y) - 1)
```

**Comment by yihuang** [comment]
Computation example:
```
n0 = exp2(-1, 1.45):

n = 14y + x*x
  = 14 * 1.45 + 1
  = 21.3
n = 10y + x*x / n
  = 10 * 1.45 + 1 / 21.3
  = 14.54694835680751173708920188
n = 6y + x*x / n
  = 6 * 1.45 + 1 / n
  = 8.768742940132322091334516702
n = 2y - x + x*x / n
  = 2 * 1.45 + 1 + 1 / n
  = 4.014041431802414064067103546
n = 1 + 2*x / n
  = 1 - 2 / n
  = 0.5017490392215644219551563224

>>> # float point arithemetic
>>> math.exp(-1/1.45)
0.5017490561548967
```

**Comment by tomtau** [comment]
Before implementing this, can you update: https://crypto-com.github.io/getting-started/staking.html ?

Docs there may be outdated -- for these sorts of things, it should be clear what's being implemented... Currently, there's some reward distribution implementation, but I'm not sure whether it  adheres to what's described in https://crypto-com.github.io/getting-started/staking.html#rewards or there's a bug?

**Comment by lezzokafka** [comment]
Was playing with the this expression, looking good!
Will adujst the value of _tau_ and it's damping rate for this.

**Comment by yihuang** [comment]
> Before implementing this, can you update: https://crypto-com.github.io/getting-started/staking.html ?
> 
> Docs there may be outdated -- for these sorts of things, it should be clear what's being implemented... Currently, there's some reward distribution implementation, but I'm not sure whether it adheres to what's described in https://crypto-com.github.io/getting-started/staking.html#rewards or there's a bug?

Current implementation adheres to current docs. This issue is to adjust the reward rate according to `reward_period_seconds/year_seconds` to keep a consistent yearly rate.
