### ISSUE TITLE
Problem: evidence age, jail time and unbonding period are not checked

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#988]
I guess this relation should be satisfied:
UNBOND_PERIOD >= JAIL_DURATION >= MAX_EVIDENCE_AGE ?

**Comment by lezzokafka** [comment]
The catch is the unit of  `MAX_EVIDENCE_AGE` is blocks, but the other two are in seconds?

**Comment by tomtau** [comment]
duplicate of #1016
